// This file is generated

I_name_0 = [
", Doris",
", Harriet",
"Abernathy, Laurence",
"Abernathy, Marjory",
"Abernathy, Orm",
"Abernethy, Alexander",
"Abernethy, Alfreka",
"Abernethy, Hugh",
"Abernethy, Margaret",
"Abernethy, Mary",
"Abernethy, Patrick",
"Abernethy, Unknown",
"Abernethy, William",
"Airth, Agnes",
"Aldrich, Carrie",
"Alsace, Maud",
"Amstel van IJsselstein, Agnes Gijsbrechtsdr van",
"Amstel van IJsselstein, Herbaren van heer van I",
"Amstel van IJsselstein, Otto van",
"Andres, Margaretha",
"Androssan, Unknown",
"Angelos, Irene Angelina",
"Angoul\u00eame, Aymer",
"Angoul\u00eame, Isabelle",
"Angus, Beth\u00f3c",
"Angus, Duncan",
"Angus, Gillbride",
"Angus, Ragnild",
"Anjou, B\u00e9atrice",
"Anjou, Blanche",
"Anjou, Charles Martel",
"Anjou, Jean",
"Anjou, Louis",
"Anjou, Maria",
"Anjou, Pierre",
"Anjou, Tristan",
"ap Gruffydd, Owain",
"ap Iorwerth, Llywarch",
"ap Iorwerth, Llywelyn",
"Ap Llewelyn, Tegwared",
"ap Llywelyn, Dafydd",
"ap Llywelyn, Gruffydd",
"ap Maredudd, Madog",
"Appelt, Chester Max",
"Appelt, Christine Adair",
"Appelt, Daniel Thomas",
"Appelt, Jason Dean",
"Aquitaine, Eleanor",
"Arag\u00f3n, Alfonso",
"Arag\u00f3n, Constanza",
"Arag\u00f3n, Fernando",
"Arag\u00f3n, Isabella",
"Arag\u00f3n, Jaime II",
"Arag\u00f3n, Jaime I",
"Arag\u00f3n, Leonor",
"Arag\u00f3n, Maria",
"Arag\u00f3n, Pedro II",
"Arag\u00f3n, Pedro III",
"Arag\u00f3n, Sancho",
"Arag\u00f3n, Yolanda",
"Arbuthnot, Hugo",
"Arens, Angela",
"Arens, Anna",
"Arens, Benjamin James",
"Arens, Bonnie",
"Arens, Bradley",
"Arens, Brian",
"Arens, Cynthia",
"Arens, Deana Marie",
"Arens, Donald",
"Arens, Donald",
"Arens, Francis",
"Arens, Francis",
"Arens, Francis A.",
"Arens, Frank",
"Arens, Ida",
"Arens, Jack Ritter",
"Arens, James",
"Arens, James Francis",
"Arens, James William",
"Arens, Jeffrey",
"Arens, Joey",
"Arens Arentz, Johannes Hermann",
"Arens, John",
"Arens, Joseph",
"Arens, Joseph",
"Arens, Katherine",
"Arens, Kathleen",
"Arens, Maren Margaret",
"Arens, Mark",
"Arens, Mary",
"Arens, Mary Rose",
"Arens, Mary Theresia",
"Arens, MaryAnn",
"Arens, Matthew",
"Arens, Michael",
"Arens, Priscilla",
"Arens, Ruth",
"Arens, Theresa",
"Arens, Thomas",
"Arens, Willhelm",
"Arens, William",
"Arens, William",
"Argyll, Duncan",
"Argyll, Eoin",
"Argyll, Ewen",
"Arkel, Johan II",
"Arkel, Johan III",
"Arkel, Johan IV",
"Arkel, Margaretha",
"Arkel, Maria",
"Armstrong, Alexander",
"Armstrong, Alexander",
"Arnsberg, Adelheid",
"Arpadhazi, Andras",
"Arpadhazi, Andr\u00e1s II",
"Arpadhazi, Anna",
"Arpadhazi, B\u00e9la",
"Arpadhazi, Erzsebet",
"Arpadhazi, Istv\u00e1n V",
"Arpadhazi, Jolanta",
"Arpadhazi, Kalman",
"Arpadhazi, Katalin",
"Arpadhazi, Maria",
"Arpadhazi, Salamon",
"Arpadhazi, Unknown",
"Artois, Blanche",
"Artois, Marguerite",
"Askey, Albert",
"Askey, Amanda",
"Askey, Ann",
"Askey, Armstrong",
"Askey, Catherine",
"Askey, David",
"Askey, David",
"Askey, David",
"Askey, Eliza",
"Askey, Eliza",
"Askey, Ellis",
"Askey, Ellis",
"Askey, Ellis",
"Askey, Ernest",
"Askey, Frank",
"Askey, Hannah",
"Askey, Hazel",
"Askey, James",
"Askey, James",
"Askey, James",
"Askey, James B",
"Askey, John",
"Askey, John",
"Askey, John",
"Askey, John",
"Askey, John Ellis",
"Askey, John Thomas",
"Askey, Joseph",
"Askey, Letitia",
"Askey, Letty Jane Lamb",
"Askey, Lizzie",
"Askey, Lucetta Allison",
"Askey, Margaret",
"Askey, Margaret",
"Askey, Mary",
"Askey, Mary",
"Askey, Mary Evoline",
"Askey, Mary Ann",
"Askey, Nancy Jane",
"Askey, Nelson",
"Askey, Nelson",
"Askey, Orpha",
"Askey, Orpha",
"Askey, Orphe",
"Askey, Rachel",
"Askey, Rachel",
"Askey, Rebecca",
"Askey, Rebecca",
"Askey, Robert A",
"Askey, Samuel",
"Askey, Sarah",
"Askey, Saran",
"Askey, Thomas",
"Askey, Thomas",
"Askey, Thomas",
"Askey, William",
"Askey, William",
"Askey, William",
"Askey, William",
"Askey, William",
"Asperen, Unknown",
"Atheyn, Mariota",
"Atholl, Henry III",
"Atholl, Malcolm",
"Atholl, Unknown",
"Aubigny, Isabel",
"Aubigny, Maud",
"Aubigny, William",
"Auchinleck, John",
"Auchinleck, Marion",
"Austolo, Philip DeSancto",
"Auvergne, Jeanne I",
"Auvergne, Maria",
"Avenel, Roger",
"Avenel, Unknown",
"Avesnes, Agnes d'",
"Avesnes, Aleida",
"Avesnes, Aleidis",
"Avesnes, Alix",
"Avesnes, Baudouin",
"Avesnes, Baudouin D'",
"Avesnes, Bouchard",
"Avesnes, Bouchard D' [Bishop of",
"Avesnes, Floris d'",
"Avesnes, Geertruid",
"Avesnes, Guillaume d'",
"Avesnes, Guillaume II-IV",
"Avesnes, Guy",
"Avesnes, Henri D'",
"Avesnes, Ida D'",
"Avesnes, Isabel",
"Avesnes, Isabella",
"Avesnes, Isabelle D'",
"Avesnes, Jacques",
"Avesnes, Jan",
"Avesnes, Jean",
"Avesnes, Jean",
"Avesnes, Jean",
"Avesnes, Jeanne D'",
"Avesnes, Jeanne D' [Abbess of",
"Avesnes, Johanna",
"Avesnes, Louis",
"Avesnes, Marguerite",
"Avesnes, Marguerite D'",
"Avesnes, Maria",
"Avesnes, Marie",
"Avesnes, Marie",
"Avesnes, Sibylla",
"Avesnes, Simon D' Seigneur",
"Bagot, Wiliam Knt",
"Bagot, William",
"Baillie, Marion",
"Baker, Abram",
"Baker, Anne",
"Baker, Elizabeth",
"Baker, Elizabeth",
"Baker, Elizabeth Betsey",
"Baker, George",
"Baker, George Peter",
"Baker, Hannah",
"Baker, Henry",
"Baker, Isaac",
"Baker, Jacob",
"Baker, Jacob",
"Baker, Jacob",
"Baker, Joel",
"Baker, John",
"Baker, John Robert",
"Baker, Leah",
"Baker, Lemon",
"Baker, Mary",
"Baker, Peter",
"Baker, Rebecca",
"Baker, Rebecca",
"Baker, Rosannah",
"Baker, Samuel",
"Baker, Susan",
"Baker, William",
"Balliol, Ada",
"Balliol, Laura",
"Banastre, Maud",
"Bar Le Duc, Sibylle",
"Bar-le-Duc, Henri",
"Bar-le-Duc, Marguerithe",
"Bar-le-Duc, Theobald",
"Bar-le-Duc, Thibault",
"Bar-Pierrepont, Elisabeth",
"Bar-Pierrepont, Theobald",
"Barcelona, Alfonso",
"Barclay, David",
"Barclay, David",
"Barclay, Effie",
"Barclay, Jean",
"Barclay, Joneta",
"Barkley, Margaret",
"Barton, Edith",
"Basset, Alice",
"Basset, Aline",
"Batail, Constance",
"Bavaria, Ludwig VI 'der R\u00f6mer' van",
"Bayern, Catharina",
"Bayern, Mechtild",
"Beaton, David",
"Beaton, Janet",
"Beauchamp, Alicia",
"Beauchamp, Anne or Amy",
"Beauchamp, Ela",
"Beauchamp, Guy",
"Beauchamp, Isabel",
"Beauchamp, Isabel",
"Beauchamp, Joan",
"Beauchamp, John",
"Beauchamp, John",
"Beauchamp, Margaret",
"Beauchamp, Matilda",
"Beauchamp, Robert",
"Beauchamp, Sarah",
"Beauchamp, Sybil",
"Beauchamp, Thomas",
"Beauchamp, Walter",
"Beauchamp, Walter",
"Beauchamp, William",
"Beauchamp, William",
"Beauchamp, William",
"Beaufort, Edmund KG",
"Beaufort, Henry",
"Beaufort, Henry",
"Beaufort, Jean",
"Beaufort, Joan",
"Beaufort, Joan LG",
"Beaufort, John KG",
"Beaufort, John KG",
"Beaufort, Margaret",
"Beaufort, Thomas",
"Beaumont, Alice",
"Beaumont, Henri Knt",
"Beaumont, Henry",
"Beaumont, Isabel",
"Beaumont, John",
"Beaumont, Margaret",
"Beherns, Elizabeth",
"Beieren, Beatrix",
"Beieren, Elisabeth",
"Beieren, Margaretha",
"Beieren, Otto V Keurvorst",
"Beieren Wittelsbach, Albrecht II",
"Beieren Wittelsbach, Anna",
"Beighler, Elizabeth",
"Bellenden, Margaret",
"Bennet, Edwin",
"Bennet, Elizabeth",
"Bennet, John",
"Bennett, John",
"Bereng, Eleanor",
"Berg, Engelbert",
"Berkeley, Agnes",
"Berkeley, Euphemia",
"Berkeley, Hugh",
"Berkeley, Humphrey",
"Berkeley, John",
"Berkeley, Margaret",
"Berkeley, Roger",
"Berkeley, Theobald",
"Berkeley, Walter",
"Berthout, Floris",
"Berthout, Sophia",
"Berthout, Wouter",
"Beste, Maria Theresia",
"Bigod, Hugh",
"Bigod, Hugh",
"Bigod, Isabel",
"Bigod, Joan",
"Bigod, Ralph",
"Bigod, Roger",
"Bigod, Roger",
"Biset, Margaret",
"Bisset, Cecilia",
"Bisset, John",
"Bisset, John",
"Black, Frank",
"Blois, Thibaut",
"Blum, Anna Gertrude",
"Boddens, Catherine",
"Boehmer, Casper",
"Boehmer, Ignatius",
"Boehmer, Joan",
"Boehmer, Leona",
"Boehmer, Ralph",
"Bohemia, Anna Princess Of",
"Bohemia, Dagmar",
"Bohemia, Otakar",
"Bohun, Mary LG",
"Bolebec, Isabel",
"Bonkyl, Alexander",
"Bonkyl, Margaret",
"Bonkyl, Randolph",
"Bonkyll, Adam",
"Bonner, Rachel",
"Borthwick, Janet",
"Borthwick, William",
"Borthwick, William",
"Borthwick, William",
"Boteler, Matilda",
"Botiller, Theobald",
"Bourbon, Beatrice",
"Bourbourg, Beatrix",
"Bourgogne, Agn\u00e8s",
"Bourgogne, Alfonso Alfonsez",
"Bourgogne, Alix",
"Bourgogne, Anne",
"Bourgogne, Anne",
"Bourgogne, Antoine",
"Bourgogne, Berengaria",
"Bourgogne, Berenguela",
"Bourgogne, Bonne",
"Bourgogne, Catherine",
"Bourgogne, Charles",
"Bourgogne, Felipe",
"Bourgogne, Fernando",
"Bourgogne, Hugues de (IV)",
"Bourgogne, Isabelle",
"Bourgogne, Jean",
"Bourgogne, Jeanne",
"Bourgogne, Jeanne",
"Bourgogne, Jeanne",
"Bourgogne, Louis",
"Bourgogne, Luis Prince of",
"Bourgogne, Marguerite",
"Bourgogne, Marguerite",
"Bourgogne, Marie",
"Bourgogne, Marie",
"Bourgogne, Philippe",
"Bourgogne, Philippe",
"Bourgogne, Robert II de",
"Bourgogne, Urraca",
"Boyd, Alan",
"Boyd, Alexander",
"Boyd, James",
"Boyd, James",
"Boyd, James",
"Boyd, Margaret",
"Boyd, Margaret",
"Boyd, Margaret",
"Boyd, Margaret",
"Boyd, Margeret",
"Boyd, Marion",
"Boyd, Mary",
"Boyd, Robert",
"Boyd, Robert",
"Boyd, Robert",
"Boyd, Simon",
"Boyd, Thomas",
"Boyd, Thomas",
"Boyd, Thomas",
"Boyd, Thomas",
"Boyd, Thomas",
"Boyd, William",
"Boyd, William",
"Boyd, William of Badenheath",
"Brabant, Beatrix",
"Brabant, Elisabeth",
"Brabant, Elisabeth",
"Brabant, Henri",
"Brabant, Henri",
"Brabant, Henri",
"Brabant, Henri",
"Brabant, Henry IV",
"Brabant, Jan",
"Brabant, Jan I",
"Brabant, Jean",
"Brabant, Jeanne",
"Brabant, Margaret",
"Brabant, Margaret",
"Brabant, Marguerite",
"Brabant, Marie",
"Brabant, Marie",
"Brabant, Marie",
"Brabant, Mathilde",
"Brabant, Mathilde",
"Brabant, Phillip",
"Brandenburg, Mathilde",
"Braose, Margaret",
"Braose, Matilda",
"Braose, William",
"Braunschweig, Agnes van de Pal",
"Brechin, David",
"Brechin, Margaret",
"Brechin, William",
"Breightmet, Augustine",
"Breightmet, Cicely",
"Brewer, Anne",
"Brienne, Blanche",
"Brienne, Jean",
"Brienne, Jean",
"Briwere, Isabel",
"Briwere, Margaret",
"Bronkhorst, Maria van",
"Bruce, Alexander",
"Bruce, Allanora",
"Bruce, Beatrice",
"Bruce, Bernard",
"Bruce, Christiane",
"Bruce, Christina",
"Bruce, Christina",
"Bruce, David",
"Bruce, Edward",
"Bruce, Elizabeth",
"Bruce, Elizabeth",
"Bruce, Elizabeth",
"Bruce, Elizabeth",
"Bruce, Euphemia",
"Bruce, George",
"Bruce, John",
"Bruce, John",
"Bruce, Lena",
"Bruce, Margaret",
"Bruce, Margaret",
"Bruce, Margerie",
"Bruce, Mary",
"Bruce, Mary",
"Bruce, Matilda",
"Bruce, Neil",
"Bruce, Richard",
"Bruce, Robert",
"Bruce, Robert",
"Bruce, Robert",
"Bruce, Robert",
"Bruce, Robert",
"Bruce, Robert The Compet",
"Bruce, Walter",
"Bruce, William",
"Brus, Alexander",
"Brus, Christina",
"Brus, Edward",
"Brus, Eupheme",
"Brus, Isabel",
"Brus, Isabel",
"Brus, Margaret",
"Brus, Matilda",
"Brus, Nigel",
"Brus, Richard",
"Brus, Thomas",
"Brus, William",
"Buchan, Colban",
"Buchan, Eva",
"Buchan, Fergus Colban",
"Buchan, Margaret",
"Burbach, Anna Maria",
"Burbach, Anna Maria",
"Burbach, Catherine",
"Burbach, Henry",
"Burbach, Jacob",
"Burbach, Joseph",
"Burbach, Joseph",
"Burbach, Leona",
"Burbach, Ludwig Hubert",
"Burbach, Mathias",
"Burbach, Mathias",
"Burbach, Peter",
"Burgh, Agatha",
"Burgh, Alice",
"Burgh, Aveline",
"Burgh, Edmond",
"Burgh, Egidia",
"Burgh, Elayne",
"Burgh, Eleanor",
"Burgh, Elizabeth",
"Burgh, Hubert",
"Burgh, Joan",
"Burgh, John",
"Burgh, Katherine",
"Burgh, Margery",
"Burgh, Matilda",
"Burgh, Maud",
"Burgh, Miss",
"Burgh, Richard",
"Burgh, Richard",
"Burgh, Richard Knt",
"Burgh, Thomas",
"Burgh, Walter",
"Burgh, Walter Knt",
"Burgh, William",
"Burgh, William",
"Burgh, William",
"Burgundy, Margaret",
"Byset, Muriel",
"Cairnes, Catherine",
"Caithness, Isabella of",
"Calderwood, Janet",
"Cameron, Allan",
"Cameron, Jean",
"Cameron, John",
"Cameron, John",
"Cameron, John",
"Cameron, John Ochtery",
"Cameron, Margaret",
"Cameron, Marion",
"Cameron, Mariota",
"Cameron, Robert",
"Cameron, Robert",
"Campbell, Agnes",
"Campbell, Alicia",
"Campbell, Amabilla",
"Campbell, Andrew",
"Campbell, Annabella",
"Campbell, Archibald",
"Campbell, Archibald",
"Campbell, Archibald",
"Campbell, Archibald",
"Campbell, Archibald",
"Campbell, Archibald",
"Campbell, Beatrice",
"Campbell, Catherine",
"Campbell, Catherine",
"Campbell, Catherine",
"Campbell, Catherine",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, Colin",
"Campbell, dau of Sir Colin",
"Campbell, Donald",
"Campbell, Donald",
"Campbell, Dougal",
"Campbell, Dougal Mor",
"Campbell, Dugal",
"Campbell, Dugald",
"Campbell, Dugald",
"Campbell, Duncan",
"Campbell, Duncan",
"Campbell, Duncan",
"Campbell, Duncan",
"Campbell, Duncan",
"Campbell, Duncan",
"Campbell, Elizabeth",
"Campbell, Elizabeth Isabella of Loudoun",
"Campbell, George",
"Campbell, George",
"Campbell, George",
"Campbell, George",
"Campbell, Giles",
"Campbell, Gillespic",
"Campbell, Gwine",
"Campbell, Helen",
"Campbell, Helen",
"Campbell, Hucheon",
"Campbell, Hugh",
"Campbell, Hugh",
"Campbell, Hugh",
"Campbell, Ian Dubh",
"Campbell, Isabel",
"Campbell, Isabella",
"Campbell, Isabella",
"Campbell, Janet",
"Campbell, Jean",
"Campbell, Jean",
"Campbell, John",
"Campbell, John",
"Campbell, John",
"Campbell, John",
"Campbell, John",
"Campbell, John",
"Campbell, Katherine",
"Campbell, Margaret",
"Campbell, Margaret",
"Campbell, Margaret",
"Campbell, Mariota",
"Campbell, Mariota Margaret",
"Campbell, Mary",
"Campbell, Mary",
"Campbell, Moir",
"Campbell, Neil",
"Campbell, Neil",
"Campbell, Neil",
"Campbell, Sir Dougall",
"Campbell, Thomas",
"Campbell, Unknown",
"CAMPBELL Earl of Atholl, John",
"Campbell of Lochow, Unknown",
"Cantilupe, Mabel",
"Cantilupe, Nichole",
"Cantilupe, William",
"Capet, Agnes",
"Capet, Agn\u00e8s Princess",
"Capet, Alix",
"Capet, Alphonse",
"Capet, Alphonse",
"Capet, Blanche",
"Capet, Blanche",
"Capet, Blanche",
"Capet, Blanche",
"Capet, Charles",
"Capet, Charles",
"Capet, Charles",
"Capet, Charles I",
"Capet, Eleanor",
"Capet, Etienne",
"Capet, Isabelle",
"Capet, Isabelle",
"Capet, Isabelle",
"Capet, Jean",
"Capet, Jean",
"Capet, Jean",
"Capet, Jean Tristan",
"Capet, Louis",
"Capet, Louis",
"Capet, Louis",
"Capet, Louis",
"Capet, Louis",
"Capet, Louis",
"Capet, Marguerite",
"Capet, Marguerite",
"Capet, Marguerite",
"Capet, Philippe",
"Capet, Philippe",
"Capet, Philippe",
"Capet, Philippe",
"Capet, Philippe",
"Capet, Philippe Auguste",
"Capet, Philippe Dagobert",
"Capet, Pierre",
"Capet, Robert",
"Capet, Robert",
"Capet, Robert",
"Capet, Robert",
"Capet, Robert de",
"Capet, Stillborn",
"Capet, Unknown",
"Cardny, Marion",
"Carlile, Christian",
"Carpenter, Clara",
"Carpentier, Godefroy",
"Carrick, Alexander",
"Carrick, Allan",
"Carrick, Duncan",
"Carrick, Errick",
"Carrick, John",
"Carrick, Marjorie",
"Carrick, Martha",
"Carrick, Niall",
"Carrick, Rignach",
"Carrick, Thomas",
"Castile, Henry",
"Castile, Manuel",
"Castile, Simon",
"Castile, Ximen",
"Castilla, Alfonso",
"Castilla, Alfonso",
"Castilla, Alfonso",
"Castilla, Berenguela",
"Castilla, Blanca",
"Castilla, Constanza LG",
"Castilla, Enrique",
"Castilla, Fadrique",
"Castilla, Fernando",
"Castilla, Fernando",
"Castilla, Fernando",
"Castilla, Juan",
"Castilla, Leonor",
"Castilla, Leonor",
"Castilla, Leonor",
"Castilla, Pedro",
"Castilla y Le\u00f3n, Mar\u00eda",
"Catherine, Unknown",
"Ceva, Giorgio",
"Ceva, Guglielmo",
"Ceva, Luisa",
"Chalmer, Catherine",
"Champagne, Blanche",
"Champagne, Marie De",
"Champagne, Thibaut",
"Champagne, Thibaut",
"Ch\u00e2teaudun, Geoffroi II",
"Ch\u00e2teaudun, Jeanne",
"Ch\u00e2tillon, Beatrix",
"Ch\u00e2tillon, Guy",
"Ch\u00e2tillon, Guy",
"Ch\u00e2tillon, Hugues",
"Ch\u00e2tillon, Matilde",
"Chaucombe, Amabil",
"Chaucombe, Robert",
"Chaumont, Robert II de",
"Chaworth, Adam",
"Chaworth, Agnes",
"Chaworth, Emma",
"Chaworth, Eva",
"Chaworth, Eve",
"Chaworth, Harvey",
"Chaworth, Hervey",
"Chaworth, Maud",
"Chaworth, Pain",
"Chaworth, Pain",
"Chaworth, Patrick",
"Chaworth, Patrick",
"Chaworth, Patrick Knt",
"Chaworth, William",
"Chen, Reginald",
"Chester, Matilda",
"Cheyne, Beatrix",
"Cheyne, Christian",
"Cheyne, Freskin",
"Cheyne, Reginald",
"Chilham, Isabel",
"Clare, Agnes",
"Clare, Amice",
"Clare, Aveline",
"Clare, Eleanor",
"Clare, Gilbert",
"Clare, Gilbert",
"Clare, Isabel",
"Clare, Isabel",
"Clare, Richard",
"Clare, Richard",
"Clare, William",
"Clavering, Cecilia",
"Clavering, John",
"Clermont, Maud",
"Columbers, Alan",
"Columbers, Cecily",
"Comte d'Andria, Raymond B\u00e9renger",
"Comyn, Alexander Knt",
"Comyn, Alexander Knt",
"Comyn, Alice",
"Comyn, Aymer",
"Comyn, Bridget",
"Comyn, Catherine",
"Comyn, Dornagilla",
"Comyn, Egidia Agnes",
"Comyn, Elena",
"Comyn, Elizabeth",
"Comyn, Elizabeth",
"Comyn, Idoine",
"Comyn, Isabel",
"Comyn, Isabel",
"Comyn, Johanna",
"Comyn, John",
"Comyn, John",
"Comyn, John",
"Comyn, John",
"Comyn, Margaret",
"Comyn, Margaret",
"Comyn, Marjorie",
"Comyn, Maud",
"Comyn, Richard",
"Comyn, Richard",
"Comyn, Roger",
"Comyn, Walter",
"Comyn, William",
"Comyn, William",
"Comyn, William",
"Concubine Of SCOTLAND, Mrs robert",
"Cond\u00e9, Isabel",
"Cond\u00e9, Nicholas",
"Corbet, Alice",
"Cornhill, Juliana",
"Cornwall, Lawrence",
"Coucy, Alix",
"Coucy, Enguerrand",
"Coucy, Enguerrand IV de",
"Coucy, Marie",
"Coucy, Raoul",
"Coucy, Raoul II De",
"Coucy, Yolande",
"Courtenay, Alix",
"Courtenay, Catherine",
"Courtenay, Philippe De",
"Courtenay, Yolande",
"Cowall, Malcolm",
"Craufurd, Hugh",
"Craufurd, John",
"Crawford, Alyse",
"Crawford, Andrew",
"Crawford, Archibald",
"Crawford, Daughter",
"Crawford, Gualterus",
"Crawford, John",
"Crawford, Margaret",
"Crawford, Mistress",
"Crawford, Mrs Hugh",
"Crawford, Reginald",
"Crawford, Reginald",
"Crawford, Reginald",
"Crawford, Reginald",
"Crawford, Roger",
"Crawford, Susan",
"Crichton, Christian",
"Crichton, Christian",
"Crichton, Edna",
"Crichton, Edward",
"Crichton, Edward",
"Crichton, Elizabeth",
"Crichton, George",
"Crichton, James",
"Crichton, Janet",
"Crichton, Margaret",
"Crichton, Margaret",
"Crichton, Nicholas",
"Crichton, Patrick",
"Crichton, Robert",
"Crichton, Robert",
"Crichton, Robert",
"Crichton, Stephen",
"Crichton, Thomas",
"Crichton, Thurston",
"Crichton, William",
"Crichton, William",
"Crichton, William",
"Croy, In\u00eas",
"Cuser, William",
"Cuyck, Kunigunde",
"D Espinay, Anne",
"D Humieres, Louise",
"d' Auvergne et de Boulogne, Guillaume XII X",
"d' Avesnes, Geertruid",
"D' Evreux, Marguerite",
"d'Ancerville, Yolande",
"d'Anjou, Philippe I",
"d'Anjou, Robert",
"d'Artois, Marie",
"Dafydd, Miss Verch",
"Dafydd, Rhys Ap",
"Dammartin, Agnes",
"Dammartin, Alberic",
"Dammartin, Jeanne",
"Dammartin, Philippa",
"Dammartin, Simon",
"Dampierre, Archambaud X",
"Dampierre, Guillaume",
"Dampierre, Guillaume",
"Dampierre, Guy III",
"Dampierre, Helvide",
"Dampierre, Jean",
"Dampierre, Jean I",
"Dampierre, Jeanne De",
"Dampierre, Louis de",
"Dampierre, Louis I",
"Dampierre, Margaret",
"Dampierre, Marie",
"Dampierre, Marie",
"Danielston, Robert",
"Danzielstour, Joanna",
"de Arbuthnot, Philip",
"De Arderne, Nichola",
"De Balsac, Guillaume",
"De Balsac, Katherine",
"De Balsac, Pierre",
"de BAR, Erard",
"de Batail, William",
"de Bataille, Henry",
"de Berkeley, Roger",
"De Bonkyl, Margaret",
"de Bourbon, Marguerite",
"de Bourgogne, Marguerite",
"De Bourgogne, Philippe",
"de Bourgogne Valois, Catherine",
"de Boyt, Robert ancestor of Portincross",
"De Brabant, Godefroy",
"de Brechin, Henry",
"de Burgh, Jill Egidia",
"De Caithness, Isabella",
"de Cambrai, Jean VI",
"de Cambrun, John",
"de Carrick, Gilbert",
"de Carrick, Roland",
"de Champagne, Marguerite",
"De Contay, Francoise",
"De Crawford, Hugh",
"de Dampierre, Louis",
"De Dampierre, Marguerite",
"de Flamville, Constance",
"de GOURLAY, William",
"de Graham, Henry",
"De Graham, Margaret",
"De Graham, Peter",
"De Gueldres, Agnes",
"de Hepburn, Nicholas",
"de Hibburne, Adam",
"De Hybourne, Robert",
"de Ireby, Christina",
"De La Queuille, Anne",
"De La Queuille, Francois",
"De Leon, Aldonza",
"De Leslie, Margaret",
"De Lindsay, John",
"De Lyon, Jean",
"de Mauduit, William",
"De Moray, Margaret",
"de Muschamp, Robert I",
"De Namur, Henri IV",
"De Rethel, Jeanne",
"de Roskelyn, Amicia",
"de Ross, Joanna",
"de Rumigny, Isabella",
"de Strathearn, Helen",
"De Stratherne, Malise Earl",
"de Toucy, Jeanne",
"de Vere, Alphonse",
"de Vere, Aubrey",
"de Vere, Gilbert",
"de Vere, Hawise",
"de Vere, Hugh",
"de Vere, Isabel",
"de Vere, Joan",
"de Vere, Lora",
"de Vere, Maud",
"de Vere, Richard",
"de Vere, Robert",
"de Vere, Robert",
"de Vere, Robert",
"de Vere, Simon",
"De Vesci, Maud",
"de Warren, Margaret",
"deAvesnes, Marie",
"DeBar, Marguerite",
"DeBar Sur Seine, Ermesinde",
"DeBurgh, Gibon",
"DeBurgh, Thomas",
"DeGalloway, Alicia",
"DeHerries, Robert",
"DeL Isle, Unknown",
"DeLeon, Sancha",
"DeLisle, Reignaldsdatter",
"della Scalla, Regina",
"DeMenteith, Gilchrist",
"DeMenteith, Murdach",
"DeMentieth, Isabella",
"Demontgomerie, Anne de",
"Demontgomerie, Joanna de",
"DeRoss, Intagart",
"Despencer, Juliana",
"Despenser, Aline",
"Despenser, Elizabeth",
"Despenser, Hugh",
"Despenser, Hugh",
"Despenser, Hugh KB",
"Despenser, Isabel",
"Despenser, Isabel",
"Despenser, Margaret",
"Despenser, Philip Knt",
"Despenser, Rohese",
"Detott, Jacquelina",
"Detott, Jacquelina Juvitot",
"DeVaux, Madam",
"Dinan, Hawise",
"Douglas, Agnes",
"Douglas, Andrew",
"Douglas, Archibald",
"Douglas, Archibald",
"Douglas, Archibald",
"Douglas, Archibald",
"Douglas, Archibald",
"Douglas, Barbara",
"Douglas, Catherine",
"Douglas, Christian",
"Douglas, Egidia",
"Douglas, Eleanor",
"Douglas, Eleanor",
"Douglas, Elizabeth",
"Douglas, Elizabeth",
"Douglas, Elizabeth",
"Douglas, George",
"Douglas, Helen",
"Douglas, Henry",
"Douglas, Hugh",
"Douglas, Hugh",
"Douglas, Isabel",
"Douglas, James",
"Douglas, James",
"Douglas, James",
"Douglas, James",
"Douglas, James",
"Douglas, James",
"Douglas, James Earl of Av",
"Douglas, Jane",
"Douglas, Janet",
"Douglas, Janet Dalkeith",
"Douglas, Joan",
"Douglas, Joanna",
"Douglas, John",
"Douglas, John",
"Douglas, Margaret",
"Douglas, Margaret",
"Douglas, Margaret",
"Douglas, Margaret",
"Douglas, Margaret",
"Douglas, Margery",
"Douglas, Mary",
"Douglas, Mary",
"Douglas, Muriel",
"Douglas, Nicholas",
"Douglas, Unknown",
"Douglas, Unknown",
"Douglas, Willelma",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William",
"Douglas, William Knt",
"Dreux, Alice",
"Dreux, Blanche",
"Dreux, Eleanor",
"Dreux, Marie",
"Dreux, Philippa",
"Dreux, Robert",
"Dreux, Yolande",
"Drinckam, Count Johann of",
"Drummond, Annabella",
"Drummond, Anne",
"Drummond, Beatrix",
"Drummond, David",
"Drummond, John",
"Drummond, John",
"Drummond, John",
"Drummond, John",
"Drummond, Malcolm",
"Drummond, Malcolm",
"Drummond, Malcolm",
"Drummond, Malcolm",
"Drummond, Malcolm",
"Drummond, Thomas",
"Drummond, William",
"Duchess of Cleves, Elizabeth",
"Duddingston, Janet",
"Duffus, Walter",
"Dunbar, Agnes",
"Dunbar, Agnes",
"Dunbar, Agnes",
"Dunbar, Alexander",
"Dunbar, Alexander",
"Dunbar, Alice",
"Dunbar, Cecilia",
"Dunbar, Cecily",
"Dunbar, Columba",
"Dunbar, David",
"Dunbar, David",
"Dunbar, Elizabeth",
"Dunbar, Elizabeth",
"Dunbar, Gavin (Gawyn)",
"Dunbar, George",
"Dunbar, George",
"Dunbar, George",
"Dunbar, George De",
"Dunbar, Gunnild",
"Dunbar, Hugh De",
"Dunbar, Janet",
"Dunbar, Janet",
"Dunbar, Janet",
"Dunbar, John",
"Dunbar, John",
"Dunbar, John",
"Dunbar, John",
"Dunbar, Margaret",
"Dunbar, Margaret De",
"Dunbar, Margaret of Dunbar of Marche",
"Dunbar, Marjory",
"Dunbar, Nicholas",
"Dunbar, Patrick",
"Dunbar, Patrick",
"Dunbar, Patrick",
"Dunbar, Patrick",
"Dunbar, Patrick",
"Dunbar, Patrick",
"Dunbar, Patrick",
"Dunbar, Patrick V",
"Dunbar, Sybil",
"Dunbar, Waltheof",
"Dunkeld, Bethoc",
"Dunkeld, Helen de Lisle",
"Dunkeld, Henry",
"Dunkeld, Henry",
"Dunkeld, Malcolm",
"Dunkeld, Robert",
"Earl Menteith Earl, Walter",
"Eben-Brockschmidt, Maria Katherina",
"Edmonston, John Knight",
"Edmonston, Margaret",
"Edmonstone, Archibald",
"Edmonstone, Christian",
"Edmonstone, John Knight",
"Edmonstone, William",
"Edmonstone, William",
"Edmundiston, Henricus",
"Edmundiston, Henry",
"Eglington, Radalphus De of Eglington",
"Eglinton, Elizabeth",
"Eglinton, Hugh",
"Egmond, Aleid van",
"Egmond, Arnoud",
"Egmond, Claes (Nicolaas) van",
"Egmond, Gerard",
"Egmond, Jan",
"Egmond, Jan van",
"Egmond, Margaretha",
"Egmond, Sophia van",
"Egmond, Willem",
"Egmond, Willem III heer van",
"Egmond, Wouter II heer van",
"Egmond-Gelre, Catharina",
"Egmond-Gelre, Maria",
"Egmond-Gelre, Willem",
"Ellmaker, Leonard",
"Elverdinghe, Count Robert of",
"Ergadia, Alan",
"Ergadia, Eoin",
"Ericsdottir, Ingibiorg",
"Erskine, Agnes",
"Erskine, Alan",
"Erskine, Alexander",
"Erskine, Alexander",
"Erskine, Alexander",
"Erskine, Alexander",
"Erskine, Alice",
"Erskine, Andrew",
"Erskine, Annabell",
"Erskine, Annabella",
"Erskine, Anne",
"Erskine, Arthur",
"Erskine, Arthur",
"Erskine, Catherine",
"Erskine, Charles",
"Erskine, Charles",
"Erskine, Christian",
"Erskine, Christian",
"Erskine, Christian",
"Erskine, Christian",
"Erskine, Christina",
"Erskine, David",
"Erskine, David",
"Erskine, Elizabeth",
"Erskine, Elizabeth",
"Erskine, Helen",
"Erskine, Henry",
"Erskine, Henry",
"Erskine, Henry",
"Erskine, Henry",
"Erskine, Henry",
"Erskine, Isobel",
"Erskine, James",
"Erskine, James",
"Erskine, Janet",
"Erskine, Janet",
"Erskine, Janet",
"Erskine, Janet of Mar",
"Erskine, Jean",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John",
"Erskine, John Douglas",
"Erskine, Katherine",
"Erskine, Katherine",
"Erskine, Lucy",
"Erskine, Margaret",
"Erskine, Margaret",
"Erskine, Margaret",
"Erskine, Margaret",
"Erskine, Margaret",
"Erskine, Mariot",
"Erskine, Mary",
"Erskine, Mary",
"Erskine, Mary",
"Erskine, Mary",
"Erskine, Nicholas",
"Erskine, Robert",
"Erskine, Robert",
"Erskine, Robert",
"Erskine, Robert",
"Erskine, Thomas",
"Erskine, Thomas",
"Erskine, Thomas",
"Erskine, Thomas",
"Erskine, Unknown",
"Erskine, William",
"Erskine, William",
"Erskine, William",
"Erskine, William",
"Erskine, William",
"Erskine, William",
"Erskine, William",
"Erskine of Mar, Margaret",
"Erskine of Mar, Robert",
"Erwin, Maude Lee",
"Este, Aldobrandino",
"Este, Menzia",
"Eumont, Elizabeth",
"Eumont, Elizabeth",
"Evans, Col. William",
"Evans, Elizabeth Betty",
"Evans, Polly Mary",
"Evreux, Marie",
"Fahling, Josephine",
"Faslane, Walter",
"Faunes, Anabel",
"Fawnys, Christian",
"Fenton, Alice",
"Fenton, William",
"ferch Gruffudd, Susanna",
"ferch Llewelyn, Elen",
"ferch Llywarch, Tangwystl",
"ferch Llywelyn, Gwenllian",
"ferch Llywelyn, Gwladus",
"ferch Llywelyn, Margaret",
"ferch Llywelyn, Susanna",
"ferch Madog, Marared",
"Fern\u00e1ndez, Berenguela",
"Fern\u00e1ndez, Pedro",
"Fernandez, Sancho",
"Ferrers, Bertha",
"Ferrers, William",
"Ferrers, William",
"Fert\u00e9, Gundred",
"Fert\u00e9, William",
"Fiennes, Enguerrand KB",
"Fiennes, Giles",
"Fiennes, Jean",
"Fiennes, Joan",
"Fiennes, Margaret",
"Fiennes, Maud",
"Fiennes, Maud",
"Fiennes, Robert",
"Fiennes, William",
"Fiennes, William",
"Fife, Afreka",
"Fife, Duncan",
"Fife, Isabel",
"Fines, Reginald de",
"Fitz Walter, David",
"FitzAlan, Alasia",
"FitzAlan, Alice",
"FitzAlan, Alice LG",
"FitzAlan, Aline",
"FitzAlan, Amy",
"FitzAlan, Avelina",
"FitzAlan, Edmund",
"FitzAlan, Edmund",
"FitzAlan, Edmund",
"FitzAlan, Eleanor",
"FitzAlan, Eleanor",
"FitzAlan, Eleanor",
"FitzAlan, Elizabeth",
"FitzAlan, Eva",
"FitzAlan, Isabel",
"FitzAlan, Jane",
"FitzAlan, Joan",
"FitzAlan, John",
"FitzAlan, John",
"FitzAlan, John",
"FitzAlan, John",
"FitzAlan, John",
"FitzAlan, John",
"FitzAlan, John V",
"FitzAlan, Katherine",
"FitzAlan, Katherine",
"FitzAlan, Leonard",
"Fitzalan, Margaret",
"FitzAlan, Margaret",
"FitzAlan, Margaret",
"FitzAlan, Mary",
"FitzAlan, Matilda",
"Fitzalan, Maud",
"FitzAlan, Maud",
"FitzAlan, Philippa",
"FitzAlan, Ranulph",
"FitzAlan, Richard",
"FitzAlan, Richard",
"FitzAlan, Richard KG",
"FitzAlan, Simon",
"FitzAlan, Thomas",
"FitzAlan, Walter",
"FitzGeoffrey, John",
"FitzHugh, Robert",
"FitzHugh, Sarah",
"Fitzjames, Jean",
"FitzJohn, Aveline",
"FitzJohn, Isabel",
"FitzJohn, Joan",
"FitzJohn, Joan",
"FitzJohn, John",
"FitzJohn, Maud",
"FitzJohn, Richard",
"FitzOsbert, Margaret",
"FitzOsbert, Walter",
"FitzPiers, Geoffrey",
"Fitzreginald, Mary",
"FitzReinfrid, Gilbert",
"FitzRoy, Henry",
"FitzRoy, Isabel",
"FitzRoy, Richard",
"FitzUchtred, Eve",
"FitzWalter, Alan",
"FitzWalter, David",
"FitzWaltheof, Uctred",
"FitzWarin, Eve",
"FitzWarin, Eve",
"FitzWarin, Fulk",
"FitzWilliam, Amice",
"Flanders, Johanna de",
"Fleming, David",
"Fleming, David",
"Fleming, Faith",
"Fleming, Faith",
"Fleming, Janet",
"Fleming, Malcolm",
"Fleming, Malcolm of Biggar",
"Fleming, Malcolm of Fulwood",
"Fleming, Patrick of Biggar",
"Fleming, Patrick of Bord",
"Fleming, Robert",
"Forbes, Margaret",
"Forez, Guigone",
"Forrester, Adam",
"Forrester, Adam",
"Forrester, Janet",
"Forrester, John",
"Forrester, Margaret",
"Forrester, Margaret",
"Forz, Aveline",
"Forz, William",
"Fourbour, Mariota",
"Fox, Eliza",
"Fraser, Alexander",
"Fraser, Alexander",
"Fraser, Andrew",
"Fraser, Christina",
"Fraser, Eda",
"Fraser, Finetta",
"Fraser, Joan",
"Fraser, John",
"Fraser, John",
"Fraser, Margaret",
"Fraser, Maria",
"Fraser, Mary",
"Fraser, Richard",
"Fraser, Simon",
"Fraser, Simon",
"Fraser, Simon",
"Fraser, Simon",
"Fraser, UNKNOWN",
"Fraser, William",
"Freitzheim, Anna Margaretta",
"Furnival, Gerald Knt",
"Furnival, Thomas",
"Galfridus, Unknown",
"Galicia, Mstislawna",
"Galloway, Ada",
"Galloway, Alan",
"Galloway, Christian",
"Galloway, Daughter Of",
"Galloway, Dervorguilla",
"Galloway, Dervorguille",
"Galloway, Ellen",
"Galloway, Eve",
"Galloway, Gilbert",
"Galloway, M",
"Galloway, Margaret",
"Galloway, Marian",
"Galloway, Roland",
"Galloway, Thomas",
"Galloway, Thomas",
"Galloway, Uchtred",
"Galloway, UNKNOWN",
"Gelre, Aleid",
"Gelre, Margaretha",
"Gelre, Otto",
"Gelre, Reinald",
"Gen\u00e8ve, Beatrix",
"Gernon, Hugh",
"Giffard, Hugh",
"Giffard, Hugh",
"Giffard, Hugh",
"Giffard, Janet",
"Giffard, Janet",
"Giffard, John",
"Giffard, John",
"Giffard, John",
"Giffard, William",
"Gifford, Alice",
"Gifford, Hugh",
"Gifford, Hugh",
"Gifford, Hugo Hugh",
"Gifford, Janet",
"Gifford, Janet Jean",
"Gifford, William",
"Gifford, William",
"Gil de Soverosa, Teresa",
"Gilbertsson, Magnus",
"Gilchrist, Gilbert",
"Gilchrist, Magnus",
"Gilchrist, Magnus II",
"Gillebride, Gillebride",
"Gillebrigte, Matilda",
"Gilronan, Mac",
"Gourlay, Christian",
"Gournay, Millicent",
"Graham, Annabella",
"Graham, David",
"Graham, David",
"Graham, David",
"Graham, David",
"Graham, David",
"Graham, David",
"Graham, David",
"Graham, Euphemia",
"Graham, Euphemia",
"Graham, Henry",
"Graham, Henry",
"Graham, Henry",
"Graham, Idonea",
"Graham, Isabel",
"Graham, John",
"Graham, John",
"Graham, John",
"Graham, John",
"Graham, John",
"Graham, Lady Isabel",
"Graham, Margaret",
"Graham, Margaret",
"Graham, Margaret",
"Graham, Margaret",
"Graham, Nicholas",
"Graham, Patrick",
"Graham, Patrick",
"Graham, Patrick",
"Graham, Peter",
"Graham, Robert",
"Graham, Unknown",
"Graham, Unknown",
"Graham, Unknown",
"Graham, Walter",
"Graham, William",
"Graham, William Kincaide",
"Greystoke, Alice",
"Gu\u00f0r\u00f8\u00f0arson, Olaf II the Black V",
"Gu\u00f0r\u00f8\u00f0arson, \u00d3l\u00e1fr",
"Guines, Adelize",
"Gu\u00eenes, Arnoul",
"Gu\u00eenes, Arnoul",
"Gu\u00eenes, Baudouin",
"Guines, Margaret",
"Guise, Adele",
"Guisnes, Enguerrand",
"Gulik, Johanna",
"Gwynedd, Iorweth",
"Haakonsdottir, Ingeborg",
"Habsburg, Anna",
"Habsburg, Jutta Judith van Oostenrijk van",
"Habsburg, Mechtild",
"Hainault, Margaretha",
"Hainault, Valeran de",
"Hainaut, Baudoin IX-VI-I",
"Hainaut, Guillaume",
"Hainaut, Isabelle de",
"Hainaut, Philippa",
"Hainaut, Unknown",
"Haliburton, Adam",
"Haliburton, Henry",
"Haliburton, Jean",
"Haliburton, Jean",
"Haliburton, John",
"Haliburton, John",
"Haliburton, Philip",
"Haliburton, Walter",
"Haliburton, William",
"Halliday, Katherine",
"Hamilton, Agnes",
"Hamilton, Alexander",
"Hamilton, Catherine",
"Hamilton, David",
"Hamilton, David",
"Hamilton, Elizabeth",
"Hamilton, Elizabeth",
"Hamilton, Elizabeth",
"Hamilton, Gavin",
"Hamilton, Gavin",
"Hamilton, Helen",
"Hamilton, James",
"Hamilton, James",
"Hamilton, James",
"Hamilton, James",
"Hamilton, James",
"Hamilton, Joanna",
"Hamilton, John",
"Hamilton, John",
"Hamilton, John",
"Hamilton, John",
"Hamilton, Margaret",
"Hamilton, Margery Catherine",
"Hamilton, Marjory",
"Hamilton, Mary",
"Hamilton, Robert",
"Hamilton, Robert",
"Hamilton, Walter",
"Haraldsson, John I",
"Harrison, Jane",
"Hastings, Alice",
"Hatcher, Jane",
"Hay, Alice",
"Hay, Jean",
"Hay, Margaret",
"Hay, William",
"Haya, Idonea",
"Heimes, Albert Anton",
"Heimes, Anton",
"Heimes, Clara Josephine",
"Heimes, Gilbert Joseph",
"Heimes, Joseph Edward",
"Heimes, Leonard Francis",
"Heimes, Monica Mathilda",
"Heimes, Rita Marie",
"Heimes, Teresa Josephine",
"Heimes, William",
"Heimes, William Frederick",
"Henegouwen, Margaret",
"Hengebach, Godfried",
"Hepburn, Adam",
"Hepburn, Adam",
"Hepburn, Agnes",
"Hepburn, Agnes Nmn-Patrick",
"Hepburn, Alexander",
"Hepburn, Archibald",
"Hepburn, Elizabeth",
"Hepburn, George",
"Hepburn, Helen",
"Hepburn, Margaret",
"Hepburn, Patrick",
"Hepburn, Patrick",
"Hepburn, Patrick",
"Hepburn, Patrick",
"Hepburn, William",
"Hepburn, William",
"Heriz, William",
"Herren, Trentjia",
"Herries, Herbert",
"Herries, Janet",
"Herries, John",
"Herries, John",
"Herries, John",
"Herries, Marian",
"Herries, Mariot",
"Herries, Mary",
"Herring, Giles",
"Herring, John",
"Hobelheinrich, Elizabeth",
"Hohenstaufen, Constanza",
"Hohenstaufen, Elisabeth",
"Hohenstaufen, Manfred",
"Hohenstaufen, Maria",
"Hohenstaufen, Philip",
"Holand, Adam",
"Holand, Alan",
"Holand, Avena",
"Holand, Isabel",
"Holand, Joane",
"Holand, John KG",
"Holand, Margery",
"Holand, Matthew",
"Holand, Otho KG",
"Holand, Robert",
"Holand, Robert",
"Holand, Robert",
"Holand, Robert",
"Holand, Thomas",
"Holand, Thomas KG",
"Holand, Thurstan",
"Holand, William",
"Holland, Adam",
"Holland, Adam",
"Holland, Alan",
"Holland, Aleida",
"Holland, Alianore",
"Holland, Avena",
"Holland, Berthe",
"Holland, Bridget",
"Holland, Edmund",
"Holland, Edmund KG",
"Holland, Eleanor",
"Holland, Eleanor",
"Holland, Elinor",
"Holland, Elizabeth",
"Holland, Elizabeth",
"Holland, Elizabeth",
"Holland, Floris",
"Holland, Floris",
"Holland, Hendrik",
"Holland, Joan",
"Holland, Joan LG",
"Holland, Machteld",
"Holland, Margaret",
"Holland, Margaret",
"Holland, Margaret",
"Holland, Margaret",
"Holland, Margaretha",
"Holland, Margart",
"Holland, Matilda",
"Holland, Matthew",
"Holland, Maud",
"Holland, Maud",
"Holland, Richard",
"Holland, Richard",
"Holland, Robert",
"Holland, Roger",
"Holland, Roger",
"Holland, Thomas KG",
"Holland, Willem",
"Holland, Willem",
"Holland, William",
"Holzbauer, Joseph",
"Holzbauer, Ofillia",
"Home, Alexander",
"Home, Elizabeth",
"Hope, Anne",
"Hope, Edward",
"Hope, Henry",
"Hope, James",
"Hope, John",
"Hope, John",
"Hope, Marie",
"Hope, Thomas",
"Hope, Thomas",
"Hose, Christiana",
"Hose, John",
"Hose, Walter",
"Humieres, Jean D",
"Hungary, L\u00e1szl\u00f3",
"Huntingdon, Ada",
"Huntingdon, Ada",
"Huntingdon, David",
"Huntingdon, David",
"Huntingdon, Henry",
"Huntingdon, Isabelle",
"Huntingdon, John",
"Huntingdon, Margaret",
"Huntingdon, Marjory",
"Huntingdon, Matilda",
"Huntingdon, Unknown",
"Huntington, Unknown",
"Hywel, Dafydd Ap",
"IJsselstein, Jan van",
"IJsselstein, Willem van kanunnik t",
"Isaac, Catherine",
"Isaac, Joan",
"Isaac, Joanna",
"Isaac, Thomas",
"Isabel, Isabel",
"Isle, Helen",
"Isles, Agnes",
"Isles, Ragnhild",
"Johnson, Thomas",
"Johnston, Mary",
"Johnstone, Adam",
"Johnstone, Gilbert",
"Johnstone, John",
"Johring, Anna Caroline",
"Johring, Benjamin Henry",
"Jonsdottir, Joan",
"J\u00fclich, Elizabeth",
"Julich, Gerard",
"J\u00fclich, Gerhard VI",
"J\u00fclich, Margarethe",
"Julich, Wilhelm",
"Julich, Wilhelm",
"J\u00fclich, Wilhelm VII",
"J\u00fclich, Wilhelm II",
"Kaiser, Elizabeth",
"Kaiser, Jacob",
"Kaiser, John",
"Keimmerling, Cecelia",
"Keith, Christiana",
"Keith, Edward",
"Keith, Elizabeth",
"Keith, Elizabeth",
"Keith, Elizabeth",
"Keith, Hervey",
"Keith, Janet",
"Keith, Janet",
"Keith, John",
"Keith, John",
"Keith, Malcolm",
"Keith, Margaret",
"Keith, Muriella",
"Keith, Philip",
"Keith, Richard",
"Keith, Robert",
"Keith, Robert",
"Keith, Robert",
"Keith, Sir Alexander",
"Keith, Sir John",
"Keith, William",
"Keith, William",
"Kellet, Adam",
"Kellet, Anna",
"Kellet, Osbert",
"Kellet, Unknown",
"Kennedy, Alexander",
"Kennedy, Elizabeth",
"Kennedy, Elizabeth",
"Kennedy, Gilbert",
"Kennedy, Gilbert",
"Kennedy, Gilbert of Dunure",
"Kennedy, James",
"Kennedy, James",
"Kennedy, James of Dunure",
"Kennedy, John",
"Kennedy, John",
"Kennedy, John",
"Kennedy, Katherine",
"Kennedy, Margaret",
"Kennedy, Marion",
"Kennedy, Mary",
"Kennedy, Mary",
"Kennedy, Robert",
"Kennedy, Walter",
"Kent, Helen",
"Kent, Robert",
"Ker, Nichole",
"Kieth, Elizabeth",
"Kilmarnock, Catherine",
"Kleinschimdt, Mary",
"Kleinschimdt, Peter",
"Kleve, Adolf",
"Kleve, Dietrich",
"Kleve, Irmgard",
"Kleve, Katharina",
"Kleve, Otto",
"Kleve-Mark, Elizabeth von",
"Klinkher, Theresa",
"Kneifl, Agnes",
"Koch, Anna Marie",
"Kramer, Margaret",
"Kumania, Erzsebet",
"Kumania, Kuthen",
"Lacy, Alice",
"Lacy, Egidia",
"Lacy, Gilbert",
"Lacy, Hugh",
"Lacy, Margery",
"Lacy, Maud",
"Lacy, Roger",
"Lacy, Rohese",
"Lacy, Walter",
"Lacy, Walter",
"Lamont, Christina",
"Lamont, Duncan",
"Lamont, John",
"Lamont, Laumon",
"Lamont, Malcolm",
"Lamont, Mary",
"Lamont, Robert",
"Lancaster, Alicia",
"Lancaster, Avice",
"Lancaster, Avice",
"Lancaster, Blanche",
"Lancaster, Edward",
"Lancaster, Elizabeth LG",
"Lancaster, Hawise",
"Lancaster, Henry KG",
"Lancaster, Isabel",
"Lancaster, Katherine LG",
"Lancaster, Philippa LG",
"Lancaster, Thomas KG",
"Lancaster, Thomas KG KB",
"Lascaris, Maria",
"Lascelles, Ermina",
"Le Carpentier, Baudoin",
"le Cheyne, Reginald II",
"Le Scot, Unknown",
"Leise, Unknown",
"Leitch, Moira",
"Leith, Elizabeth",
"Lemon, Elizabeth",
"Lennox, Ada",
"Lennox, Donald",
"Lennox, Donnchadh",
"Lennox, Donnchadh of",
"Lennox, Elizabeth",
"LennoX, Isabel of Lennox",
"Lennox, Malcolm",
"Lennox, Malcolm",
"Lennox, Maldouen",
"Lennox, Maol Choluim",
"Lennox, Margaret",
"Lennox, Margaret",
"Lennox, Mary",
"Lennox, Unknown",
"Le\u00f3n, Urraca",
"Leon and Castile, Constanza",
"Leslie, Alexander",
"Leslie, Andrew",
"Leslie, Andrew",
"Leslie, Bartholomew",
"Leslie, George",
"Leslie, Malcolm",
"Leslie, Margaret",
"Leslie, Mariota",
"Leslie, Mary",
"Leslie, Norino",
"Leslie, Norino",
"Leslie, Norman",
"Leslie, Norman",
"Leslie, Norman",
"Leslie, Walter",
"Lesmaye, Catherine",
"Levington, Matilda",
"Limburg, Henri",
"Limburg, Henrik",
"Limburg, Mathilde",
"Limburg, Sofie",
"Limburg, Waleram",
"Limburg, Waleram",
"Limesi, Eleanor",
"Lindsay, Alexander",
"Lindsay, Alexander",
"Lindsay, Alexander",
"Lindsay, Alexander",
"Lindsay, Alice",
"Lindsay, Beatrice",
"Lindsay, Christian",
"Lindsay, David",
"Lindsay, David",
"Lindsay, David",
"Lindsay, David",
"Lindsay, David",
"Lindsay, David",
"Lindsay, David",
"Lindsay, Elizabeth",
"Lindsay, Elizabeth",
"Lindsay, Eufemia",
"Lindsay, Eupheme",
"Lindsay, Gerard",
"Lindsay, Gilbert",
"Lindsay, Ingelram",
"Lindsay, Isabella",
"Lindsay, James",
"Lindsay, James",
"Lindsay, John",
"Lindsay, John",
"Lindsay, Margaret",
"Lindsay, Margaret",
"Lindsay, Marjorie",
"Lindsay, Reginald",
"Lindsay, Walter",
"Lindsay, Walter",
"Lindsay, Walter",
"Lindsay, Walter",
"Lindsay, Walter",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William",
"Lindsay, William Knight",
"Lindsey, John H",
"Lindsey, Margaret",
"Lisle, Dugall",
"Livingston, Alexander III",
"Livingston, Andrew",
"Livingston, Janet",
"Livingston, John I",
"Livingston, William",
"Llewellyn, Angharad",
"Llewelyn, Tegwared y Baiswen",
"Llywarch, Gwladys ferch",
"Llywarch, Tangwystl",
"Llywelyn, Helen",
"London, Hawise",
"London, Thomas",
"Londres, Maurice",
"Longesp\u00e9e, Ela",
"Longesp\u00e9e, Emmeline",
"Longesp\u00e9e, Ida",
"Longesp\u00e9e, Stephen",
"Looz, Aleidis",
"Lorens, Eda",
"Lorens, Hugh",
"Lorraine, Cunegonde",
"Lorraine, Isabel",
"Lorraine, Thibault",
"Loudin, Eschina",
"Loudon, James",
"Loudon, Margaret",
"Louvain, Godfrey",
"Louvain, Matthew",
"Louvain, Matthew",
"Louvain, Thomas",
"Lovaine, Eleanor",
"Lucembursk\u00e1, Eliska",
"Lucy, Geoffrey",
"Lucy, Geoffrey",
"Lucy, Geoffrey",
"Lucy, Maud",
"Lusignan, Agn\u00e8s",
"Lusignan, Alice",
"Lusignan, Aymer",
"Lusignan, Geoffroi",
"Lusignan, Guy",
"Lusignan, Hugues",
"Lusignan, Hugues IX",
"Lusignan, Hugues XI",
"Lusignan, Isabella",
"Lusignan, Isabelle",
"Lusignan, Marguerite De",
"Lusignan, William",
"Luxembourg, Charles",
"Luxembourg, G\u00e9rard",
"Luxembourg, Henri",
"Luxembourg, Henri",
"Luxembourg, Isabel de",
"Luxembourg, Jean",
"Luxembourg, Jutta",
"Luxembourg, Marie",
"Luxembourg, Philippa",
"Luxembourg, Venceslas I",
"Luxembourg, Waleran",
"Lyle, Aaron",
"Lyle, Andrew",
"Lyle, Isabell",
"Lyle, Margaret",
"Mac Kennedy, Fergus",
"mac Raghnaill, Ruairi",
"MacCrotan, Fionghuala",
"Maccuswell, Aymer",
"Maccuswell, Herbert",
"MacDonald, Agnes",
"Macdonald, Alexander",
"Macdonald, Alexander",
"Macdonald, Alexander",
"MacDonald, Alexander",
"Macdonald, Amie",
"Macdonald, Angus",
"Macdonald, Angus",
"Macdonald, Angus",
"MacDonald, Angus",
"MacDonald, Anne",
"MacDonald, Aonghas",
"Macdonald, Donald",
"Macdonald, Elizabeth",
"MacDonald, Finvola",
"MacDonald, Florence",
"Macdonald, Godfrey",
"Macdonald, Hugh",
"MacDonald, James",
"MacDonald, Jean",
"Macdonald, John",
"Macdonald, John",
"Macdonald, John",
"Macdonald, John",
"MacDonald, John Mor Tanister",
"Macdonald, Margaret",
"MacDonald, Mariot",
"MacDonald, Mary",
"MacDonald, Mary",
"MacDonald, Mora",
"MacDonald, Ranald",
"Macdonald, Somerled",
"Macdonald, Unknown",
"MacDonnell, Marcus",
"Macdougal, John",
"Macdougall, Alexander",
"MacDougall, Catherine",
"MacDougall, Duncan",
"MacDougall, Isabel",
"MacDougall, Janet",
"Macdougall, John",
"MacDougall, Juliana",
"MacDougall, Malcolm",
"MacDougall, Mary",
"Macduff, Colbran",
"Macduff, Duncan",
"MacDuff, Eoghin",
"Macduff, Malcolm",
"MacEanruig, Unknown",
"MacFergus, Bethoc",
"MacGillebride, Gille brigte Somerld",
"Macgillebride, Somerled",
"Macgillivrail, Findoig",
"MacGillivrail, Nachtan",
"MacGillvray, Margaret",
"Macgilronan, Gilronan",
"Macgilronan, Margaret",
"MacGorrie, Arthur",
"MacGorrie, Christina",
"Mackay, Donald",
"Mackay, Iye",
"MacLaren, Unknown",
"MacLeod, Malcolm",
"MacLeod, Tormod",
"Macrory, Jean",
"Macrory, S\u00e9amus",
"Macruari, Amie",
"Macruari, Roderick",
"MacSomarlidasson, Dubhgal",
"MacSomerled, Angus",
"Macsomerled, Bethag",
"MacSomerled, Ranald",
"MacTaggart, Fearchar",
"Madison, Ann",
"Madison, George",
"Madison, George Henry",
"Madison, Richard Henry",
"Madison, Roy Leonard",
"Magnus, John",
"Magnusson, Godred",
"Maillet, Anne",
"Maitland, John",
"Maitland, Mary",
"Maitland, Robert",
"Malise, UNKNOWN I, 39th Ja",
"Malise, UNKNOWN II, 40th J",
"Mar, Alesta",
"Mar, Alexander Of",
"Mar, Domhnall",
"Mar, Donald",
"Mar, Donnchadh",
"Mar, Duncan",
"Mar, Ellen",
"Mar, Gratney",
"Mar, Isabell",
"Mar, Margaret",
"Mar, Margaret",
"Mar, Margaret",
"Mar, Margaret",
"Mar, Marjory",
"Mar, Morgg\u00e1n",
"Mar, Orabillis",
"Mar, Thomas",
"Mar, Uilleam",
"Mark, Adolf",
"Mark, Engelbert",
"Mark, Machteld",
"Mark Kleef en Gulik, Margarethe van de",
"Marshal, Eva",
"Marshal, Isabel",
"Marshal, Maud",
"Marshal, William",
"Martinez da Silva, Aldonza Martinez",
"Marx, Franz Joseph",
"Marx, Gertrude",
"Matilda, Matilda",
"Mauduit, Isabel",
"Maxwell, Agnes",
"Maxwell, Agnes",
"Maxwell, Agnes",
"Maxwell, Alexander",
"Maxwell, Alexander",
"Maxwell, Ann",
"Maxwell, Aymer",
"Maxwell, Catherine",
"Maxwell, Catherine",
"Maxwell, Edward",
"Maxwell, Edward Tinwald",
"Maxwell, Egidia",
"Maxwell, Elizabeth",
"Maxwell, Eustace",
"Maxwell, Helen",
"Maxwell, Herbert",
"Maxwell, Herbert",
"Maxwell, Herbert",
"Maxwell, Herbert",
"Maxwell, Herbert",
"Maxwell, Jane",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, John",
"Maxwell, Lady Jane",
"Maxwell, Margaret",
"Maxwell, Margaret",
"Maxwell, Mariota",
"Maxwell, Robert",
"Maxwell, Robert",
"Maxwell, Robert",
"Maxwell, Robert",
"Maxwell, Robert Knt",
"Maxwell, Robert de",
"McGee, Margaret",
"McGinley, Daniel",
"Mearns, Mary",
"Mearns, Roland",
"Mendoza, In\u00e9s I\u00f1iguez",
"Menteith, Alan",
"Menteith, Christian",
"Menteith, Eva",
"Menteith, Gille Crist",
"Menteith, Helena Lennox",
"Menteith, Joan",
"Menteith, John",
"Menteith, Margaret",
"Menteith, Mary",
"Menteith, Mary",
"Menteith, Murdoch",
"Menteith, Murdoch",
"Menteith, Walter",
"Meschines, Maud",
"Meuller, Englebert",
"MicKibben, Lettie",
"Mistress, Unknown",
"Montealto, Ellen",
"Montfalto, Ellen",
"Montfichet, William",
"Montfichet, William",
"Montfichet, William",
"Montfort, Beatrix",
"Montfort, Bertrade",
"Montfort, Jean",
"Montgomerie, Alan",
"Montgomerie, Alexander",
"Montgomerie, Alexander",
"Montgomerie, Anna",
"Montgomerie, Joanna",
"Montgomerie, John",
"Montgomerie, Margaret",
"Montgomerie, Margaret",
"Montgomerie, Murthaw",
"Montgomery, Agnes",
"Montgomery, Agnes",
"Montgomery, Alan",
"Montgomery, Alan",
"Montgomery, Alexander",
"Montgomery, Alexander de",
"Montgomery, Alexander Montgomery, Master of Montgomery",
"Montgomery, Elizabeth",
"Montgomery, Elizabeth",
"Montgomery, George",
"Montgomery, Hugh",
"Montgomery, Hugh",
"Montgomery, Isabel",
"Montgomery, Isabella",
"Montgomery, John",
"Montgomery, John",
"Montgomery, John",
"Montgomery, John",
"Montgomery, Marjory De",
"Montgomery, Mary",
"Montgomery, Neil",
"Montgomery, Rissa",
"Montgomery, Robert",
"Montgomery, Thomas",
"Montgomery, Thomas",
"Montgomery, Unknown",
"Montgomery, William",
"Montifex, Mary Margaret",
"Montmirail, Jean",
"Montmirail, Marie",
"Montpellier, Marie",
"Moravia, Kenneth",
"Moravia, Mary",
"Moravia, William",
"Moravia, William",
"Moravia, William",
"Moray, Alexander",
"Moray, Andrew",
"Moray, Andrew",
"Moray, Fonia",
"Moray, Hugh",
"Moray, Johana",
"Moray, John",
"Moray, John",
"Moray, Maurice",
"Moray, Ranulf",
"Moray, Thomas",
"Moray, William",
"Moray, William",
"Mordington, Agnes",
"Mordington, Peter",
"More, Katherine",
"Morgan, Ansel",
"Morgan, Betty Marie",
"Morgan, Herbert Merrill",
"Morgan, Merrill",
"Morgan, Ross Llewellyn",
"Morham, Adam",
"Morham, Euphemia",
"Morham, Thomas",
"Morialmes, Isabel",
"Mortimer, Edmund Knt",
"Mortimer, Geoffrey",
"Mortimer, Isabella",
"Mortimer, Isolde",
"Mortimer, Joane",
"Mortimer, Margaret",
"Mortimer, Ranulph",
"Mortimer, Ranulph",
"Mortimer, Roger",
"Mortimer, Roger Knt",
"Mortimer, William",
"Morville, Elena",
"Morville, Richard",
"Mowat, Janet",
"Moyer, Luzetta",
"Moyer, Samuel",
"Mure, Adam",
"Mure, Adam",
"Mure, Adam",
"Mure, Alicia",
"Mure, Andrew",
"Mure, Andrew",
"Mure, Anicia",
"Mure, Archibald",
"Mure, Christian",
"Mure, David",
"Mure, Elizabeth",
"Mure, Elizabeth",
"Mure, Gilchrist",
"Mure, Gilcrist",
"Mure, John",
"Mure, John",
"Mure, John",
"Mure, Jonet",
"Mure, Margaret",
"Mure, Reynold",
"Mure, Robert",
"Mure, Ronald",
"Mure, William",
"Murray, Andrew",
"Murray, Andrew",
"Murray, Annabella",
"Murray, Margaret",
"Murray, Margaret",
"Murray, Margaret",
"Murray, Margaret",
"Murray, Mrs William",
"Murray, William",
"Murray, William",
"Murray, William",
"Muschamp, Isabel",
"Muschamp, Marjory",
"Muschamp, Robert II",
"Muschampe, Cecelia",
"N., Ne.",
"Namur, Blanche",
"Namur, Elisabeth",
"Namur, Ermensinde",
"Namur, Guillaume I",
"Napoli, Jean di Priest",
"Napoli, Marguerite",
"Navarra, Beatrice",
"Navarra, Blanca",
"Navarra, Enrique",
"Navarre, Jeanne",
"Navarre, Teobaldo II-V",
"Nelson, Margaret Elizabeth",
"Neville, Hugh",
"Newbigging, Margaret",
"Notton, Avina",
"Notton, Gilbert",
"Notton, Gilbert",
"Notton, William",
"O'Beolan, Janet",
"O'Brien, Unknown",
"O'Cahan, Agnes",
"O'Cahan, Guy",
"O'Cathain, Donal",
"O'Cathain, Eachmarcach",
"O'Cathain, Magnus",
"O'Cathain, Raudria",
"of Castile, Alphonso X",
"of Castile, Berengaria",
"of Castile, Ferdinand",
"of Castile, Ferdinand",
"of Castile, Frederick",
"of Castile, Philip",
"of Castile, Sancho",
"Of Cleves, Catherine",
"of Durham, Emme",
"of Glenorchy, John",
"of Glenorchy, Mariota",
"of Luxembourg, Jan Jindrich",
"of Rothes, Watson",
"Of Scotland, Joan",
"of Swabia, Elizabeth",
"Ogilvie, Gille Cr\u00edst",
"Ogilvie, Mary",
"Olafsdatter, Ragnhilda",
"Olafsson, Magnus",
"Olafsson, R\u00f6gnvaldr",
"Orkney, Jarl David of",
"Orkney, Matilda",
"Orm, UNKNOWN",
"Padilla, Mar\u00eda",
"Peith, Elizabeth",
"Peitz, Johannes",
"Peitz, Theresa",
"Pentland, David",
"Pentland, William",
"Perche, Helisant",
"Perche, Thomas",
"Perche, Thomas",
"Pettit, Florence",
"Piast, Agnes",
"Piast, Anna",
"Piast, Beatrix",
"Piast, Boleslaw",
"Piast, Bolko",
"Piast, El\u017cbieta",
"Piast, Hedwig",
"Piast, Hedwig",
"Piast, Heinrich",
"Piast, Heinrich",
"Piast, Heinrich",
"Piast, Heinrich",
"Piast, Heinrich",
"Piast, Leszek",
"Piast, Ludwig",
"Piast, Margareta",
"Piast, Nikolaus",
"Piast, Przemislaw",
"Piast, Salomea",
"Piast, Wac\u0142aw I",
"Plantagenet, Adam",
"Plantagenet, Alice",
"Plantagenet, Alice",
"Plantagenet, Alphonse",
"Plantagenet, Beatrice",
"Plantagenet, Berengere",
"Plantagenet, Blanche",
"Plantagenet, Blanche",
"Plantagenet, Blanche",
"Plantagenet, Edmund",
"Plantagenet, Edmund",
"Plantagenet, Edmund",
"Plantagenet, Edmund KG",
"Plantagenet, Edward",
"Plantagenet, Edward",
"Plantagenet, Edward",
"Plantagenet, Edward",
"Plantagenet, Edward K.G.",
"Plantagenet, Eleanor",
"Plantagenet, Eleanor",
"Plantagenet, Eleanor",
"Plantagenet, Eleanor",
"Plantagenet, Eleanor",
"Plantagenet, Eleonore",
"Plantagenet, Elizabeth",
"Plantagenet, Eudo",
"Plantagenet, Geofrey",
"Plantagenet, Hamelin",
"Plantagenet, Henry",
"Plantagenet, Henry",
"Plantagenet, Henry",
"Plantagenet, Henry",
"Plantagenet, Henry",
"Plantagenet, Henry",
"Plantagenet, Henry KG",
"Plantagenet, Isabel",
"Plantagenet, Isabel",
"Plantagenet, Isabel",
"Plantagenet, Isabel",
"Plantagenet, Isabella",
"Plantagenet, Isabella LG",
"Plantagenet, Ivo",
"Plantagenet, Jane",
"Plantagenet, Joan",
"Plantagenet, Joan",
"Plantagenet, Joan",
"Plantagenet, Joan",
"Plantagenet, Joan",
"Plantagenet, Joan LG",
"Plantagenet, Joan of England",
"Plantagenet, Joanna",
"Plantagenet, Johanna",
"Plantagenet, John",
"Plantagenet, John",
"Plantagenet, John",
"Plantagenet, John",
"Plantagenet, John",
"Plantagenet, John",
"Plantagenet, John",
"Plantagenet, John KG",
"Plantagenet, Katherine",
"Plantagenet, Katherine",
"Plantagenet, Lionel KG",
"Plantagenet, Margaret",
"Plantagenet, Margaret",
"Plantagenet, Margaret",
"Plantagenet, Margaret",
"Plantagenet, Mary",
"Plantagenet, Mary",
"Plantagenet, Mary",
"Plantagenet, Mary",
"Plantagenet, Maud",
"Plantagenet, Oliver",
"Plantagenet, Osbert",
"Plantagenet, Richard",
"Plantagenet, Richard",
"Plantagenet, Richard",
"Plantagenet, Robert",
"Plantagenet, Thomas",
"Plantagenet, Thomas",
"Plantagenet, Thomas",
"Plantagenet, Thomas KG",
"Plantagenet, Unknown",
"Plantagenet, Unknown",
"Plantagenet, Unknown Daughter",
"Plantagenet, William",
"Plantagenet, William",
"Plantagenet, William",
"Ponthieu, Guillaume",
"Ponthieu, Marie",
"Poyntz, Maud",
"P\u0159emysl, V\u00e1clav",
"P\u0159emyslovna, Eli\u0161ka",
"P\u0159emyslovna, Mark\u00e9ta",
"Preston, Janet",
"Preston, Mary",
"Preuilly, Agatha de",
"Provence, Beatrice",
"Provence, Eleanor",
"Provence, Marguerite",
"Provence, Raimund",
"Provence, Raymond",
"Provence, Sancha",
"Quarantley, Elene",
"Quincy, Anne",
"Quincy, Elizabeth",
"Quincy, Ellen",
"Quincy, Hawise",
"Quincy, Hawise",
"Quincy, Joan",
"Quincy, Margaret",
"Quincy, Robert",
"Quincy, Roger",
"Quincy, Saher",
"Ragnaldsson, Donald",
"Ragnvaldsson, Olavus",
"Randolph, Agnes",
"Randolph, Isabel",
"Randolph, Isobel",
"Randolph, John",
"Randolph, John",
"Randolph, Thomas",
"Randolph, Thomas",
"Randolph, Thomas",
"Ranhael, William",
"Ravensberg, Margaret",
"Redvers, Isabel",
"Reginaldsdatter, Unknown",
"Reginar, Gillis",
"Reginar, Jan",
"Reginar, Jean",
"Reginar, Johanna",
"Reginar, John",
"Reginar, Machteld",
"Reignaldsdatter, Daughter",
"Renzhinger, Mary",
"Rethel, Helisende",
"Richilde, UNKNOWN",
"Riddel, Magdeline",
"Riddlesford, Emmeline",
"Riddlesford, Walter",
"Ritter, Charles Garfield",
"Ritter, Edna Mae",
"Ritter, Franklin W",
"Ritter, Jennie",
"Ritter Welch, Kara",
"Ritter, Lauren Scott",
"Ritter, Loren Alton",
"Ritter, Mary",
"Ritter, Vera Maude",
"Robert-the-Bruce, Unknown wife of",
"Roches, Clemence",
"Rodenlwold, Elizabeth Trentjia",
"Rodenlwold, George William",
"Rodenlwold, Werde Gerdes",
"Roet, Katherine",
"Roet, Payn",
"Roet, Phillipa",
"Rosabelle, Richard",
"Rosabelle, Rosabell",
"Ross, Aodh",
"Ross, Christina",
"Ross, Euphame",
"Ross, Euphemia",
"Ross, Euphemia",
"Ross, Hugh",
"Ross, Isabella",
"Ross, Isobel",
"Ross, Jean",
"Ross, John",
"Ross, John",
"Ross, John",
"Ross, Lilias",
"Ross, Lillas",
"Ross, Malcolm",
"Ross, Margaret",
"Ross, Margery",
"Ross, Ninian",
"Ross, Robert",
"Ross, Uilleam",
"Ross, Uilleam",
"Ross, William",
"Rouvres, Philippe de",
"Ruthven, Ethne",
"Ruthven, Lilias",
"Saarbr\u00fccken, Sophia",
"Sabran, Gersinde II De",
"Saint Clair, John",
"Saksen, Hermann I",
"Salisbury, Alice",
"Salisbury, Ela",
"Saluzzo, Agnese",
"Saluzzo, Alasia",
"Saluzzo, Alasia",
"Saluzzo, Bonifacio",
"Saluzzo, Manfredo",
"Saluzzo, Tomas",
"Saluzzo, Unknown",
"Samlesbury, Cecily",
"Samlesbury, Cecily",
"Samlesbury, Elizabeth",
"Samlesbury, Gospatrick",
"Samlesbury, Roger",
"Samlesbury, William",
"Sandilands, Marion of Calder",
"Sanford, Alice",
"Saunford, Gilbert",
"Saunford, Joan",
"Saunford, John",
"Savoie, Amadeo",
"Savoie, Beatrice",
"Savoie, B\u00e9atrice",
"Savoie, Tomasso",
"Schaefer, Elizabeth",
"Schieffer, Anna",
"Schieffer, Casper Jacob",
"Schieffer, John H.",
"Schmitz, Maria Magdalena",
"Schneider, Mary",
"Schuld, Anna Maria",
"Schumacher, Anton",
"Schumacher, Katharina",
"Scotland, Annabella",
"Scotland, Beatrix",
"Scotland, Marjorie",
"Seagrave, Adelle",
"Seaton, Janet",
"Segrave, Eleanor",
"Segrave, Gilbert Knt",
"Segrave, John",
"Segrave, Nicholas",
"Segrave, Nicholas",
"Segrave, Peter",
"Segrave, Stephen",
"Sempill, Janet",
"Seton, Adam",
"Seton, Alexander",
"Seton, Alexander",
"Seton, Alexander",
"Seton, Alexander",
"Seton, Alexander",
"Seton, Alexander",
"Seton, Alexander",
"Seton, Barbara",
"Seton, Catherine",
"Seton, Christian",
"Seton, Christina",
"Seton, Christopher",
"Seton, Christopher",
"Seton, George",
"Seton, Janet",
"Seton, Janet",
"Seton, John",
"Seton, John",
"Seton, John",
"Seton, Margaret",
"Seton, Margaret",
"Seton, Margaret",
"Seton, Marion",
"Seton, Marion",
"Seton, Philip",
"Seton, William",
"Seton, William",
"Sicilia, Beatrice",
"Sicilia, Bianca",
"Sicilia, Louis",
"Sicilia, Philippe",
"Sicily, Marie Elizabeth Isabel",
"Sicily, Robert De",
"Sigurdsdottir, Ellen",
"Sinclair, Alexander",
"Sinclair, Annabel",
"Sinclair, Arthur",
"Sinclair, Beatrice",
"Sinclair, Beatrice",
"Sinclair, Catherine",
"Sinclair, Catherine",
"Sinclair, Eleanor",
"Sinclair, Elizabeth",
"Sinclair, Elizabeth",
"Sinclair, George",
"Sinclair, Helen",
"Sinclair, Henry",
"Sinclair, Henry",
"Sinclair, Henry",
"Sinclair, Henry",
"Sinclair, John",
"Sinclair, John",
"Sinclair, Margaret",
"Sinclair, Margaret",
"Sinclair, Margaret",
"Sinclair, Marion",
"Sinclair, Marjory",
"Sinclair, Marjory",
"Sinclair, Richard",
"Sinclair, Richilde Lady of Roslin Midlothian, Scotland",
"Sinclair, Robert",
"Sinclair, Sir Oliver Roslin",
"Sinclair, Susan",
"Sinclair, Unknown",
"Sinclair, William",
"Sinclair, William",
"Sinclair, William",
"Sinclair, William",
"Sinclair, William",
"Sinclair, William",
"Sinclair, William II",
"Singleton, Matilda",
"Somerville, Egidia",
"Somerville, Elizabeth",
"Somerville, John",
"Somerville, John",
"Somerville, John",
"Somerville, John",
"Somerville, Margaret",
"Somerville, Margaret",
"Somerville, Margaret",
"Somerville, Marion",
"Somerville, Thomas",
"Somerville, Thomas",
"Somerville, Thomas",
"Somerville, Unknown",
"Somerville, Walter",
"Somerville, Walter",
"Somerville, Walter",
"Somerville, William",
"Somerville, William",
"Somerville, William",
"Somerville, William",
"Somery, Roger",
"Somery, Roger Knt",
"Southeray, John",
"Southworth, Jennie Elizabeth",
"St Clair, Catherine",
"St Clair, Henry",
"St Clair, Janet Isabel",
"St Clair, John",
"St Clair, Robert",
"St Clair, William",
"St Owen, Joan",
"Stair, Casillis",
"Stephenson, Eleanor",
"Stephenson, Frances",
"Sterkenburg, Bertrade",
"Stevenson, George",
"Steward, Alianore",
"Stewart, Agnes",
"Stewart, Agnes",
"Stewart, Alan",
"Stewart, Alan",
"Stewart, Alan",
"Stewart, Alan",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander",
"Stewart, Alexander mac Murdoch",
"Stewart, Alice",
"Stewart, Andrew",
"Stewart, Andrew",
"Stewart, Andrew",
"Stewart, Andrew",
"Stewart, Andrew",
"Stewart, Annabella",
"Stewart, Beatrice",
"Stewart, Beatrix",
"Stewart, Beatrix",
"Stewart, Catherine",
"Stewart, Catherine",
"Stewart, Catherine",
"Stewart, Catherine Kirkhill",
"Stewart, Christian",
"Stewart, Christian",
"Stewart, Christian",
"Stewart, David",
"Stewart, David",
"Stewart, David",
"Stewart, David",
"Stewart, David",
"Stewart, Dugald",
"Stewart, Duncan",
"Stewart, Edward",
"Stewart, Edward",
"Stewart, Egidia",
"Stewart, Egidia",
"Stewart, Egidia",
"Stewart, Egidia",
"Stewart, Egidia",
"Stewart, Egidia",
"Stewart, Egidia",
"Stewart, Eleanor",
"Stewart, Elena",
"Stewart, Elisabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elizabeth",
"Stewart, Elspeth",
"Stewart, Eupheme",
"Stewart, Euphemia",
"Stewart, Gabrielle",
"Stewart, Hawise",
"Stewart, Helen",
"Stewart, Hugh",
"Stewart, Isabel",
"Stewart, Isabel",
"Stewart, Isabel",
"Stewart, Isabel",
"Stewart, Isabell",
"Stewart, Isabella",
"Stewart, Isabella",
"Stewart, Isabella Elizabeth",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James",
"Stewart, James II",
"Stewart, Janet",
"Stewart, Janet",
"Stewart, Janet",
"Stewart, Jean",
"Stewart, Jean",
"Stewart, Jean",
"Stewart, Jean",
"Stewart, Jean",
"Stewart, Joan",
"Stewart, Joanna",
"Stewart, Johanna",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, John",
"Stewart, Katherine",
"Stewart, Katherine",
"Stewart, Katherine",
"Stewart, Lindsay",
"Stewart, Ludovic",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Margaret",
"Stewart, Marion",
"Stewart, Marjorie",
"Stewart, Marjory",
"Stewart, Marjory",
"Stewart, Marjory",
"Stewart, Mary",
"Stewart, Mary",
"Stewart, Mary",
"Stewart, Mary",
"Stewart, Mary",
"Stewart, Mary",
"Stewart, Matthew",
"Stewart, Matthew",
"Stewart, Maude",
"Stewart, Mungo",
"Stewart, Murdoch",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert",
"Stewart, Robert II",
"Stewart, Sybella",
"Stewart, Thomas",
"Stewart, Thomas",
"Stewart, Thomas",
"Stewart, Thomas",
"Stewart, Unknown",
"Stewart, Unknown",
"Stewart, Unknown",
"Stewart, UNKNOWN",
"Stewart, Unnamed Infant",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter",
"Stewart, Walter Bt",
"Stewart, William",
"Stewart, William",
"Stewart, William",
"Stewart, William Esq",
"Stirling, John",
"Stirling, Katherine",
"Stirling, Marjorie",
"Stirling, Unknown",
"StMARTIN, Lady Unknown",
"Strathbogie, David",
"Strathbogie, David",
"Strathbogie, Isabel",
"Strathbogie, John",
"Strathearn, Ada",
"Strathearn, Annabelle",
"Strathearn, Cecilia",
"Strathearn, Ethna",
"Strathearn, Ferquhard",
"Strathearn, Gille Brigte",
"Strathearn, Isabella",
"Strathearn, Katherine",
"Strathearn, Malise",
"Strathearn, Malise",
"Strathearn, Malise",
"Strathearn, Maol \u00cdosa",
"Strathearn, Mary",
"Strathearn, Mary",
"Strathearn, Matilda",
"Strathearn, Muriel Sparre",
"Strathearn, Robert",
"Strathearn, Rosabel",
"Strathearn, Unknown",
"Strathechin, Donald",
"Strathechin, Isabel",
"Stratherne, Joan",
"Strienen, Elisabeth van alias 'van",
"Stuart, Archibald",
"Stuart, Catherine",
"Stuart, Christian",
"Stuart, Elizabeth",
"Stuart, Elizabeth",
"Stuart, Esm\u00e9",
"Stuart, Esm\u00e9 KG",
"Stuart, Henrietta",
"Stuart, Janet",
"Stuart, Jill",
"Stuart, John",
"Stuart, Margaret",
"Stuart, Robert",
"Stuart, William",
"Stuteville, Joan",
"Stuteville, Nicholas",
"Sumarlidasson, Olaf",
"Sutherland, Alexander",
"Sutherland, Janet",
"Sutherland, John",
"Sutherland, John",
"Sutherland, Kenneth",
"Sutherland, Marion",
"Sutherland, Marjory",
"Sutherland, Robert",
"Sutherland, William",
"Swanzey, Jane",
"Swynford, Blanche",
"Swynford, Dorothy",
"Swynford, Hugh",
"Swynford, Thomas",
"Swynford, Thomas",
"Synton, Alexander",
"Synton, Alexander",
"Synton, Andrew",
"Synton, Isabella",
"Tattershall, Robert",
"Tattershall, Robert",
"the Marck, Adolph II of",
"the Marck, Eberhard II Count of",
"the Marck, Engelbert I, Count of",
"the Marck, Engelbert II of",
"Thuringia, Sophie",
"T\u00edr E\u00f3ghain, Daughter",
"T\u00edr E\u00f3ghain, Niall",
"Torres, Maria",
"Tourmignies, Berthe De",
"Tracy, Eve",
"Tracy, Henry",
"Tracy, Oliver",
"Trathbogie, S",
"Turnbull, Marguerite",
"Tynedale, Hextilda",
"Uknown, Unknown",
"Unknown, Agnes",
"UNKNOWN, Agnes",
"UNKNOWN, Aline",
"UNKNOWN, Anna",
"Unknown, Annabel",
"UNKNOWN, Annora",
"UNKNOWN, Beatrix",
"Unknown, Cecilia",
"UNKNOWN, Charles",
"Unknown, Christian",
"Unknown, Devorguilla",
"UNKNOWN, Doedijn",
"UNKNOWN, Elisabeth",
"UNKNOWN, Elisabeth",
"Unknown, Elizabeth",
"UNKNOWN, Elizabeth",
"UNKNOWN, Engelberte",
"Unknown, Henry",
"Unknown, Isabel",
"Unknown, Jeanne",
"Unknown, Joan",
"UNKNOWN, Johanne",
"UNKNOWN, Jolanthe",
"Unknown, Juliana",
"UNKNOWN, Katharina",
"UNKNOWN, Katherine",
"UNKNOWN, Ludwig V",
"UNKNOWN, Margarethe",
"UNKNOWN, Margarethe",
"Unknown, Mary",
"Unknown, Mathilda",
"UNKNOWN, Mathilda",
"UNKNOWN, Matilda",
"Unknown, Mistress",
"UNKNOWN, Mistress",
"UNKNOWN, Muriel",
"UNKNOWN, Orm",
"UNKNOWN, Pierre",
"UNKNOWN, Rainald IV",
"UNKNOWN, Rohais",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"Unknown, Unknown",
"UNKNOWN, Unknown",
"Unknown, Unnamed Mistress",
"UNKNOWN, Wenzel",
"UNKNOWN, Ymzoete",
"Valence, Joan",
"Valkenburg, Elisabeth",
"Valois, Agn\u00e8s",
"Valois, Blanca Margaretha",
"Valois, Blanche",
"Valois, Catherine",
"Valois, Catherine de (mort jeun",
"Valois, Catherine II",
"Valois, Charles",
"Valois, Charles II",
"Valois, Fils",
"Valois, Isabel de Abbesse de",
"Valois, Isabelle",
"Valois, Isabelle",
"Valois, Isabelle",
"Valois, Jean",
"Valois, Jean",
"Valois, Jeanne",
"Valois, Jeanne",
"Valois, Jeanne",
"Valois, John",
"Valois, Louis",
"Valois, Louis",
"Valois, Louis",
"Valois, Louis",
"Valois, Marguerite",
"Valois, Marguerite",
"Valois, Marie",
"Valois, Marie",
"Valois, Marie de",
"Valois, Philippe",
"Valois, Philippe",
"Valois, Philippe de",
"Valois, Unknown",
"Van Amstel, Arend",
"van Amstel, Arnoud",
"Van Amstel, Guyote",
"van Amstel van IJsselstein, Arend",
"van Amstel van Ijsselstein, Gijsbrecht",
"van Arkel, Arend",
"van Arkel, Arnoud",
"van Arkel, Elisabeth",
"van Arkel, Herbaren",
"van Arkel, Jan V",
"van Arkel, Johan",
"Van ARKEL, Johanna",
"van Arkel, Mabelia",
"van Arkel, Mechtild",
"van Arkel, Otto",
"van Arkel, Robbert",
"van Arkel, Willem",
"Van ARKEL, Willem",
"van Arkel Heukelom, Otto",
"van Beieren Straubing, Johanna Sophia",
"van Bronckhorst, Willem",
"van de Gheyne, Alida",
"van de Poele, Geertruyd Boudewynsdr",
"van den Poele, Jan Aelman",
"van der Poel, William III",
"Van Doortage, Dirk",
"van EGMOND, Albrecht",
"Van Egmond, Antonia",
"Van EGMOND, Arend",
"Van Egmond, Bartha",
"Van Egmond, Catharina",
"Van Egmond, Elisabeth",
"Van Egmond, Gerrit",
"Van Egmond, Griete",
"Van Egmond, Maria",
"Van Egmond, Willem",
"Van EGMOND, Willem",
"van Egmont, Adolf",
"van Gelre, Maria",
"van Gulik, Willem",
"van Heemstede, Mechteld",
"van Heukelom, Bertha",
"van Ijsselstein, Johanna",
"van Limburg, Catharina",
"van Meurs, Kunegunde",
"Van Strijen, Elisabeth",
"Van Strijen, Wilhelm",
"van Veene, Isabella",
"Van Voorne, Hildagonda",
"VanBrederode, Ada",
"VanDerPoel, William",
"VanDoortage, Beatrijs",
"vanEgmond, Beatrijs",
"vanEgmond, Jan I",
"vanEgmond, Walter",
"vanEgmond, Wilhelm",
"VanRanderath, Unknown",
"Vaus, John",
"Vaux, Alexander",
"Vaux, Beatrix de",
"Vaux, John",
"Vaux, John",
"Vaux, Unknown",
"Vaux, William",
"Vaux, William",
"Verch Llywelyn, Agatha",
"Verdun, Lesceline",
"Verdun, Rohese",
"Vere, Alfonsus de",
"Vere, Hugh",
"Vere, Margaret",
"Ritter Vetter, Amy",
"Vetter, Jake",
"Vetter, Maxx",
"Vianden, Filips",
"Vianden, Henrik",
"Vianden, Maria",
"Vierzon, Jeanne Isabeau",
"Virneburg, Mechtild",
"Virneburg, Robert",
"von Cleves, Elizabeth",
"von Habsburg, Rudolf",
"von Hohenberg, Gertrud",
"von Julich, Philippa",
"von Kleve, Adolf",
"von Kleve, Agnes",
"von Kleve, Helene",
"von Kleve, Johann",
"von Kleve, Margarethe",
"von Kleve, Maria",
"Von Limburg, Heinrich",
"von Schlesien-Liegnitz, Wenzel",
"VonBrederode, Ermegaerd",
"VonBrederode, William",
"Voorne, Albert",
"Voorne, Mabelia",
"Wake, Baldwin",
"Wake, Baldwin",
"Wake, Eleanor",
"Wake, Emeline",
"Wake, Hugh",
"Wake, Hugh",
"Wake, Hugh",
"Wake, Ida",
"Wake, Isabel",
"Wake, John",
"Wake, John",
"Wake, Margaret",
"Wake, Nicholas",
"Wake, Thomas",
"Wake, Unknown",
"Wake, William",
"Waleton, Cecily",
"Warenne, Ada",
"Warenne, Alice",
"Warenne, Ela",
"Warenne, Eleanor",
"Warenne, Isabel",
"Warenne, Isabella",
"Warenne, John",
"Warenne, John",
"Warenne, William",
"Warenne, William",
"Wassenberg, Reinoud II",
"Wassenberg, Richardis",
"Welch, Harlan",
"Welch, Maddison",
"Welch, Zach",
"Welf, Mechtild",
"Winton, Alan",
"Winton, Austin",
"Wittelsbach, Agnes",
"Wittelsbach, Agnes",
"Wittelsbach, Albrecht I",
"Wittelsbach, Jan I 'zonder genade'",
"Wittelsbach, Johanna van",
"Wittelsbach, Ludwig",
"Wittelsbach, Ludwig",
"Wittelsbach, Marguerite",
"Wittelsbach, Mathilde",
"Wittelsbach, Otto",
"Wittelsbach, Rudolf",
"Wittelsbach, Stephan",
"Wittelsbach, Wilhelm",
"Wittelsbach, Willem V",
"Woltering, Herman",
"Woltering, Marie Bernadine",
"Wycoff, Harriet",
"Wyntown, Alan",
"Wyntown, Alan",
"Wyntown, Alan",
"Wyntown, Alexander",
"Wyntown, Andrew",
"Wyntown, Henry",
"Yeman, Janet",
"Zouche, Alan",
"Zouche, Alan",
"Zouche, Alan",
"Zouche, Elizabeth",
"Zouche, Elizabeth",
"Zouche, Ellen",
"Zouche, Helene",
"Zouche, Henry",
"Zouche, Joyce",
"Zouche, Loretta",
"Zouche, Margaret",
"Zouche, Margery",
"Zouche, Mary",
"Zouche, Maud",
"Zouche, Oliver",
"Zouche, Roger",
"Zouche, Roger",
"Zouche, William"
]
Dwr.ScriptLoaded('dwr_db_I_name_0.js');
