// This file is generated

P_name_0 = [
", Fawley, Buckinghamshire, England",
",Cadzow,Lanarkshire,Scotland",
",Cambrai,Nord,France",
"'s-Hertogenbosch, Noord Brabant, Netherlands",
"(bur) Tintern Abbey, Chapel Hill, Monmouthshire, Wales",
"(not married) Wales",
"(young)",
"1410",
"92210 Saint-Cloud",
"Abbaye De La Joie, France",
"Abbeville, Somme, Picardie, France",
"Abbey of Santa Mar\u00eda la Real de Las Huelgas, Burgos, Castilla-Le\u00f3n, Spain",
"Abbey Saltre,Huntingtonshire,,England",
"Abercorn, West Lothian, Scotland",
"Aberdeenshire, Scotland",
"Aberffraw Castle, Anglesey, Wales",
"Aberffraw Castle, Ynys Mon, Gwynedd, Wales",
"Aberystwyth (Aber), Ceredigion, Dyfed, Wales",
"Acre, Jerusalem, Palestine",
"Ainsworth, Brown, Nebraska, United States of America",
"Aix en Provence, Bouches-du-Rhone, Provence-Alpes-Cote d'Azur, France",
"Aix En Provence, Bouches-du-Rhone, Provence-Alpes-Cote d'Azur, France",
"Aix, Bouches-du-Rhone, Provence-Alpes-Cote d'Azur, France",
"Algericas, C\u00e1diz, Andalusia, Spain",
"Altena, Westfalen, Prussia, Germany",
"Amesbury Priory, Wiltshire, England",
"Andalusia, Spain",
"Androssan, Ayrshire, Scotland",
"Angers, France",
"Angoul\u00eame, Charente, Poitou-Charentes, France",
"Anjou, Paris, Ile-de-France, France",
"Antrim, Northern Ireland, United Kingdom",
"Apulia, Italy",
"Arag\u00f3n, Espa\u00f1a",
"Aragon, Spain",
"Ardgowan Castle, Inverkip, Renfrewshire, Scotland",
"Ardrossan, Ayrshire, Scotland",
"Arkel, Gelderland, Netherlands",
"Arras",
"Arundel Castle, Sussexshire, England",
"Arundel, Essex, England, United Kingdom",
"Ashby de la Zouch Castle, Leicestershire, , England",
"Ashby de La Zouche, Leicestershire, England",
"Ashby-de La-Zouche, Leicestershire, England",
"Ashby-de-La-Zouche, Leicestershire, England",
"Asturias, Espa\u00f1a",
"Aubigny sur Nere, Berry, France",
"Aumale, Seine-Maritime, France",
"Aumale, Seine-Maritime, Haute-Normandie, France",
"Austria",
"Avellino, Campania, Italy",
"Ayrshire, Scotland",
"Balnagowan Scotland",
"Balvenie Castle, Fife, Scotland",
"Bar-le-Duc",
"Bar-le-Duc, Meuse, France",
"Barcelona, Catalonia, Spain",
"Barnstaple, Devon, England",
"Barton Seagrave, Northamptonshire, England",
"Barton, Lancashire, England",
"Barton, Leicestershire, England",
"Bassett, Rock, Nebraska, United States of America",
"Battle of Flodden, Flodden Field, Northumberland, England",
"Beaumont Palace, Oxford, England",
"Beauvais, Oise, Picardie, France",
"Bedford, Somerset, England",
"Berkhamstead Castle, Hertfordshire, England",
"Berkhamstead, Hertfordshire, England",
"Berry, France",
"Berwick upon Tweed, NBL, England",
"Besford, Tettenhall, Staffordshire, England",
"Black Torrington, Devon, England",
"Blisworth, Northampshire, England",
"Blisworth, NTH, England",
"Bolton, Lancashire, England",
"Bordeaux, France",
"Bothwell, Lanarkshire, Scotland",
"Boulogne, France",
"Bourne, Lincolnshire, England",
"Boves, Somme, France",
"Boves, Somme, Picardie, France",
"Bow Valley, Cedar, Nebraska, United States of America",
"Brabant",
"Brabant, , , Netherlands",
"Brabant, Lorraine, France",
"Brabant,Antwerp,,Belgium",
"Brabourne, Kent, England, United Kingdom",
"Brackley, Northamptonshire, ENG",
"Brandenburg",
"Braunschweig",
"Brechin, Lanarkshire, Scotland",
"Breightmet,Bolton,Lancashire,England",
"Bridgewater, Somersetshire, England",
"Brie, Ille-et-Vilaine, Bretagne, France",
"Brienne Le Chateau, Aube, Champagne, France",
"Brignoles, Var, Provence-Alpes-Cote d'Azur, France",
"Brionne, Eure, Haute-Normandie, France",
"Bristol, England (executed)",
"Brittany,,,France",
"Broughton, Roxburghshire, Scotland",
"Brown, Nebraska, United States of America",
"Buckinghamshire",
"Buckinghamshire, England",
"Buckley, Winchester, Southamptonshire, England",
"Bucks, England",
"Buda, Pest, Hungary",
"Budapest, Hungary",
"Burgos, Burgos, Castilla-Le\u00f3n, Spain",
"Burgos, Castilla-Le\u00f3n, Spain",
"buried Marham, Norfolk",
"Burstwick, Yorkshire, England",
"C\u00e1diz, Andalusia, Spain",
"Cairano, Avellino, Campania, Italy",
"Caithness, Scotland",
"Calatayud, Zaragoza, Spain",
"Cambrai,Nord-Pas-de Calais,France",
"Cambuskenneth Abbey, Stirlingshire, Scotland",
"Campania, Italy",
"Canfield, Essex, England, United Kingdom",
"Canterbury Cathedral, Canterbury, England",
"Cardross, Dunbartonshire, Scotland",
"Carlisle, United States of America",
"Carmarthenshire, Wales",
"Carnwath, Argyllshire, Scotland",
"Caroline, Virginia, United States of America",
"Carrick, Galloway, Scotland",
"Carri\u00f3n de los Condes, Palencia, Castilla-Le\u00f3n, Spain",
"Cassilis, Ayrshire, Scotland",
"Castilla-La Mancha, Spain",
"Castilla-Le\u00f3n, Spain",
"Castle Hedingham, Hedingham, Essex, England, United Kingdom",
"Catalonia, Spain",
"Catania, Sicily",
"Cavers House, Hawick, Roxburghshire, Scotland",
"Cedar, Nebraska, United States of America",
"Ceva, Cuneo, Piemonte, Italy",
"Chacombe Priory, Northamptonshire, England",
"Chalfont, Buckinghamshire, England",
"Chambeire, Cote d'Or, Bourgogne, France",
"Chamb\u00e9ry, Savoie, Rhone-Alpes, France",
"Champagne, , France",
"Champagne, Dordogne, Aquitaine, France",
"Chateau de Coucy",
"Chateau De Palencia, Valencia, Valencia, Almohadi",
"Chateau Du Loir,Sarthe,Maine Pays De La Loire,France",
"Chateau Montpensier, France",
"Ch\u00e2teau royal de Saint-Gemme",
"Ch\u00e2teau-P\u00e9lerin, Palestine",
"Chatillon-Sur-Indre, Berry, France",
"Chaucombe, Northamptonshire, , England",
"Cheshire, England",
"Chester, Cheshire, England",
"Chilesburg, Caroline, Virginia, United States of America",
"Chilham Castle, Chilham, Kent, England, United Kingdom",
"Chilham, Kent, England, United Kingdom",
"Church of the Black Friars, Pontefract",
"Citeaux Abbey, Paris, Ile-De-France, France",
"Clairefontaine, Autelbas, Luxembourg",
"Clavering, Essex, England, United Kingdom",
"Clermont-Ferrand, Puy-De-Dome, France",
"Cleves, North Rhine-Westphalia, Germany",
"Clun, Shropshire, England",
"Clydesdale,,Lanarkshire,Scotland",
"Cokehill, Worcestershire, England",
"Colne Engaine, Essex, England, United Kingdom",
"Compi\u00e8gne, Oise, Picardie, France",
"Concord, Nebraska, United States of America",
"Connecticut, United States of America",
"Constance, Cedar, Nebraska, United States of America",
"Constantinople, Turkey",
"Contracted",
"Corbeil",
"Cordieliers,Paris,Ile De France,France",
"Corneto, Macerata, Marche, Italy",
"Cornwall, Cornwall, England",
"Cosenza,Calabria,,Italy",
"Coucy, Aisne, Picardie, France",
"Courtenay, Loiret, France",
"Courtral, Flandre, Occidental, Belgium",
"Craighall Castle, Fife, Scotland",
"Craighall Scotland",
"Crawford, Lanarkshire, Scotland",
"Cremona, Italy",
"Crichton Castle, Pathhead, Midlothian, Scotland",
"Crofton, Knox, Nebraska, United States of America",
"Cuenca, Cuenca, Castilla-La Mancha, Spain",
"Culmstock, Devonshire, England",
"Cumberland, England",
"Cumberland, Pennsylvania, United States of America",
"Cuneo, Piemonte, Italy",
"Cupar Castle, Cupar, Fife, Scotland",
"Cupar, Fife, Scotland",
"Cwmaron Castle, Radnorshire,  Wales",
"Cyprus",
"Dallington, Northamptonshire, England",
"Damietta, Damietta, Egypt",
"Damietta, Egypt",
"Dammartin, Seine-et-Marne, Ile-de-France, France",
"Dampierre, Jura, France",
"Darnhall, Northwich, Cheshire, ENGLAND",
"Deeping, Lincolnshire, England",
"Denbighshire, Wales",
"Deventer, Overijssel, Netherlands",
"Devon, England",
"Devonshire, England",
"Dez, Sistan va Baluchestan, Iran",
"Dispensation",
"Dispensation, , , Scotland",
"Ditton (in Stoke Poges), Buckinghamshire in the presence of King Edward III",
"Dominican Church, Louvain",
"Donaworth",
"Dudley Castle, Staffordshire, England",
"Dunbartonshire, Scotland",
"Dunbeath Castle, Dunbeath, Caithness, Scotland",
"Dunbeath, Caithness, Scotland",
"Dundonald Castle, Dundonald, Ayrshire, Scotland",
"Dundonald, Ayrshire, Scotland",
"Dunkeld, Perthshire, Scotland",
"Dunlichtie Dunbeath Castle,Iverness,,Scotland",
"Dunstaffnage Castle, Oban, Scotland",
"East Lothian, Scotland",
"East Riding, Yorkshire, England",
"Eastington, Gloucestershire, Thornbury, Herefordshire, England",
"Edinburgh Castle, Edinburgh, Midlothian, Scotland",
"Edinburgh, Midlothian, Scotland",
"Egypt",
"Elmley Castle, Elmley, Worcestershire, England",
"Elmley Castle, Warwickshire, England",
"Elmley, Worcestershire, England",
"Emley Castle, Bedfordshire",
"ENG",
"England, United Kingdom",
"Entrage,Basse-Alpes,,France",
"Entrages,Alpes De Haute Provence,,France",
"Entragues,Basses-Alpes,,France",
"Erskine, Renfrewshire, Scotland",
"Esch Kreis, Koln, Nord Rhein-Westfalen, Germany",
"Essex, England, United Kingdom",
"Este, Tuscany",
"Esztergom, Komarom-Esztergom, Hungary",
"Esztergom, Komarom-Esztergom,,Hungary",
"Fariskur, Egypt",
"Fiennes, Artois, Pas-de-Calais",
"Fife, Scotland",
"Flandres, B\u00e9lgica",
"Foggia",
"Foggia, , , France",
"Foggia, Apulia, Italy",
"Foggia, Apulia, Italy",
"Foggia, Foggia, Apulia, Italy",
"Foix, Ariege, France",
"Fontainebleau, Isle De France, France",
"Fontevrault, Maine-et-Loire, Pays de la Loire, France",
"Forcalquier, Alpes-de-Haute-Provence, Provence-Alpes-Cote d'Azur, France",
"Fordoun, Kincardineshire, Scotland",
"Framlingham, Suffolk, England",
"France",
"France Buried Rhijnsburg, Zuid Holland, Netherlands",
"Gand, Flandre Orientale, Belgium",
"Garstang, Lancashire, England",
"Gaza",
"Geertruidenberg, Noord-Brabant, Nederland",
"Germany",
"Glamorganshire, Wales",
"G\u0142og\u00f3w",
"Gloucester, Gloucester, England",
"Gloucester, Gloucestershire, England",
"Goxhill, Lincolnshire, England",
"Great Hormede, Hertfordshire, England",
"Grey Friars Church, London, Middlesex, England, United Kingdom",
"Guadalajara",
"Guadalajara, Castilla-La Mancha, Spain",
"Guingamp, C",
"Halewood,,Lancashire,England",
"Halkhead, Renfrewshire, Scotland",
"Hamilton, Cumberland, Pennsylvania, United States of America",
"Hampshire, England",
"Hanendon, Wiltshire, England",
"Hannover, Prussia, Germany",
"Hanslope, Buckinghamshire, England",
"Hartford, Connecticut, United States of America",
"Hartington, Cedar, Nebraska, United States of America",
"Havering-atte-Bower, Essex, England, United Kingdom",
"Hawick, Roxburghshire, Scotland",
"Hedingham, Essex, England, United Kingdom",
"Heidelberg",
"Heidelberg,Baden,,Germany",
"Herven, den Bosch,Nederland",
"Hochsauerlandkreis, Germany",
"Hoddam, Dumfriesshire, Scotland",
"Holland",
"Holland, France",
"Holland, Lancashire, , England",
"Holt, Nebraska, United States of America",
"Hopetoun House, Abercorn, West Lothian, Scotland",
"H\u00f4tel d'Evreux, Paris",
"Houffalize, Luxembourg",
"Houffalize, Walloon, Luxembourg, Belgique",
"Howard, Pennsylvania, United States of America",
"Hradec Kr\u00e1lov\u00e9",
"Huesca, Aragon, Spain",
"Huesca, Huesca, Aragon, Spain",
"Huntingdon, Huntingdonshire, , England",
"Huntingdon, Huntingdonshire, ENGLAND",
"Huntingdon, Northumberland, England",
"Huntingdonshire, England",
"Hutt, Lancashire, England",
"Hy\u00e8res, Provence-Alpes-C\u00f4te d'Azur, France",
"Illinois, United States of America",
"in battle",
"Inverkip, Renfrewshire, Scotland",
"Iowa, United States of America",
"Ipswich, Suffolk",
"Island of Lochtay, Perthshire, Scotland",
"Italy",
"Jacksonville, Pennsylvania, United States of America",
"Jaffa, Palestine",
"Jerusalem, Palestine",
"Kamp, Mettmann, Nord Rhein-Westfalen, Germany",
"Kennington, near London, England",
"Kent, England, United Kingdom",
"Kermpsford, Gloucestershire, England",
"Keth Symon, East Lothian, Scotland",
"Kildrummie Castle, Aberdeenshire, Scotland",
"King's Chapel, Havering-atte-Bower, Essex, England, United Kingdom",
"Kingdom of Gwynedd",
"Kingsdown, Kent, England, United Kingdom",
"Kingsland, Herefordshire, England",
"Kircudbright, Kirkcudbrightshire, , Scotland",
"Kirkcaldy, Fife, Scotland",
"Kirkoswald, Cumberland",
"Knights, Essex, England, United Kingdom",
"Knox, Nebraska, United States of America",
"K\u00f6ln, , Nordrhein-Westfalen, Germany",
"Koln, Nord Rhein-Westfalen, Germany",
"Koln, Rheinland, Prussia, Germany",
"Kortrijk, West-Vlaanderen, Belgium",
"Kyle, Ayrshire, Scotland",
"La Rochelle, France",
"Lacock Priory, Wanborough, Wiltshire, England",
"Lamont, Argyll, Scotland",
"Lanarkshire, Scotland",
"Laurel, Nebraska, United States of America",
"Le Duc, Meuse, Lorraine, France",
"Le Duc,Meuse,Argonne Lorraine,France",
"Legnica, Wroclaw, Poland",
"Legnica,,,Poland",
"Lenn, Wiltshire, , England",
"Lenn, Wiltshire, England",
"Le\u00f3n, Castilla-Le\u00f3n, Spain",
"Le\u00f3n, Le\u00f3n, Castilla-Le\u00f3n, Spain",
"Leuven",
"Leuven, Belgi\u00eb",
"Leuven, Brabant, Netherlands",
"Leuven, Flanders, Belgium",
"Leuven, Flemish Brabant, Flanders, Belgium",
"Levisham, Yorkshire, England",
"Lewes, Surrey, England, United Kingdom",
"Lewes, Sussex, , England",
"Lewin Brzeski, Lower, Schlesien,",
"Limbourg, Belgium",
"Limburg, Limburg, Belgium, Netherlands",
"Lincoln Castle, Lincolnshire, England",
"Lincoln Cathedral, Lincoln, England",
"Lochindorb castle, Badenoch, Scotland",
"London, Middlesex, England, United Kingdom",
"Longchamp, Puy-de-Dome, Auvergne, France",
"Loosduinen, Zuid Holland, Netherlands",
"Lorrez-le-Bocage, G\u00e2tinais, France",
"Louden, Ayrshire, Scotland",
"Loughborough, Leicestershire, England",
"Louvain",
"L\u00fcneburg, Hannover, Prussia, Germany",
"Lusignan, Vienne, France",
"Lusignan, Vienne, Poitou-Charentes, France",
"Maine, Charente, Poitou-Charentes, France",
"Marburg, Hessen",
"Mason, Illinois, United States of America",
"Mayenne, Pays de la Loire, France",
"Medieval,States,Cumania,",
"Melun, France",
"Melun, Seine-et-Marne, Ile-de-France, France",
"Merzen, Osnabruck, Niedersachsen, Germany",
"Mettmann, Nord Rhein-Westfalen, Germany",
"Meuse, Argonne, Lorraine, France",
"Middlesex, England, United Kingdom",
"Midlothian, Scotland",
"MISTRESS",
"Mistress, not married",
"Modbury, Devon, England",
"Monasterie des Clarisses de l'Ave Maria, Paris",
"Monasterio Cistercio, Algericas, C\u00e1diz, Andalusia, Spain",
"monastery of Holyrood, Edinburgh, Scotland",
"Monastery of St. Nicolas D'Arene",
"Monastery of Valpara\u00edso, Peleas de Arriba, Kingdom of Castile",
"Monastery of Valpara\u00edso, Peleas de Arriba, Zamora, Castilla-Le\u00f3n, Spain",
"Montargis Abbey, Loiret, France",
"Montecatino",
"Montfort, Oise, Picardie, France",
"Montpellier, Herault, Languedoc-Roussillon, France",
"Mordington, Berwickshire",
"Moreton Corbet, Shropshire, England",
"M\u00fcnchen, Bayern",
"Munchen,Oberbayern,,Germany",
"Namur, Belgium",
"Naples, Campania, Italy",
"Naples, Naples, Campania, Italy",
"Natrona, Mason, Illinois, United States of America",
"Navarra, Spain",
"Near, Tunis, , Tunisia",
"Nebraska, United States of America",
"Newark, Nottinghamshire, England Buried: Worcester Cathedral",
"Newington, Kent, England, United Kingdom",
"Niedersachsen, Germany",
"Nijmegen, Guelders",
"Nithsdale, Dumfries-Shire, Scotland",
"Nocera Inferiore, Italy",
"Nocera, Salerno, Campania, Italy",
"Nord Rhein-Westfalen, Germany",
"Nord, Nord-Pas-de-Calais, France",
"North Molton, Devon, England",
"North Molton, Devonshire, England",
"North Riding, Yorkshire, England",
"Northamptonshire, England",
"Northamptonshire, England. Buried at Sawtry Abbey, Cambridgeshire.",
"Northern Ireland, United Kingdom",
"Notre Dame De Paris,Paris,Seine,France",
"Notton, West Riding, Yorkshire, England",
"Notton, Yorkshire, England",
"Nr Hoogwoud, Noord Holland, Netherlands",
"O'Neill, Holt, Nebraska, United States of America",
"Of 's Hertogenbo, Noord Brabant, Netherlands",
"Of 's-Hertogenbo, n-Brab., Neth.",
"Of Bar-Le-Duc, Meuse, France",
"Of Basel, Basel-Stadt, Switzerland",
"Of Cornwall, Cornwall, England",
"Of Dampierre, Jura, France",
"Of Dunbeath, Calth, Scot",
"Of Munchen, Oberbayern, Bavaria",
"Of Pembroke, Pembroke, Wales",
"Of Praha, Praha, Czechoslovakia",
"of Sheffield, Yorkshire, , England",
"Of Sicile",
"Of Stoke Bruern, Nrthmp, Engl",
"Of, 'S-Hertogenbosch, Noord-Brabrant, Netherlands",
"Of, Barcelona, Arag\u00f3n",
"of, Buda, Pest, Hungary",
"of, Elmley Castle, Worcestershire, England",
"of, Fiennes, Pas-de-Calais, France",
"Of, France",
"Of, Huntingdon, HUN, England",
"of, Lusignan, Vienne, France",
"Of, Oxford, Oxfordshire, England",
"of, Sicile",
"Of, Sicile",
"of, Stevington, Bedfordshire, England",
"Of, Stoke Bruern, Northamptonshire, England",
"Of, Toledo, Castile",
"Of, Toledo, Toledo, Spain",
"Of, Zaragoza, Zaragoza, Spain",
"Oizy, Namur, Belgium",
"Omaha, Nebraska, United States of America",
"Orkney Islands,Orkney,Scotland",
"Orkney, Orkney Islands, Scotland",
"Orkney, Orkney, Scotland",
"Osnabruck, Niedersachsen, Germany",
"Oswestry Castle, Shropshire, England",
"Oswestry, Shropshire, England",
"Oxford ,Oxfordshire, England",
"Oxford, Oxfordshire, England",
"Oxfordshire, England",
"Palace of Westminster, Westminster, London, Middlesex, England, United Kingdom",
"Palais Du Louvre, Paris, Seine, France",
"Palencia, Castilla-Le\u00f3n, Spain",
"Palestine",
"Palestine,Holy Land,,",
"Palma, Baleares, Spain",
"Pamplona, Navarra, Navarra, Spain",
"Papal Dispensation in Holland",
"Paris, Isle De France",
"Paris,Ville De Paris,,France",
"Passau",
"Pathhead, Midlothian, Scotland",
"Peleas de Arriba, Zamora, Castilla-Le\u00f3n, Spain",
"Pembroke, Wales",
"Pennsylvania, United States of America",
"Perkin, Illinois, United States of America",
"Perpignan, Pyrenees-Orienta, France",
"Perth, Perthshire, Scotland",
"Perthshire, Scotland",
"Piemonte, Italy",
"Pitchcott, Buckinghamshire, England",
"Poissy, France",
"Poissy, Isle De France, France",
"Poissy, Yvelines, France",
"Poissy, Yvelines, Ile-de-France, France",
"Poissy, Yvelines, \u00cele-de-France, France",
"Poitiers France",
"Pons, Poitou-Charentes, France",
"possibly Lincolnshire",
"Powys, Wales",
"Prob, England",
"Prussia, Germany",
"Queen's Chapel, Reading, Berkshire, England",
"Queens Chapel, Reading, Berkshire, England",
"Ralston, Renfrewshire, Scotland",
"Ravenscraig Castle, Fife, Scotland",
"Red Oak, Iowa, United States of America",
"Renfrewshire, Scotland",
"Rheinfelden",
"Rheinland, Prussia, Germany",
"Richmond, Virginia, United States of America",
"Ridott, Pennsylvania, United States of America",
"Roa, Burgos, Castilla-Le\u00f3n, Spain",
"Rochford, Essex, England, United Kingdom",
"Rock, Nebraska, United States of America",
"Roncesvalles, Navarra",
"Roquefort, near Bordeaux in France",
"Roslin, Caithness, Scotland",
"Rouen,Normandie,,France",
"Rowley Regis, Staffordshire, England",
"Roxburghshire, Scotland",
"Runcorn, Cheshire, England",
"Rutlandshire, England",
"S-Gravenhage, Zuid Holland, Netherlands",
"Salamanca, Castilla-Le\u00f3n, Spain",
"Salamanca, Salamanca, Castilla-Le\u00f3n, Spain",
"Salerno, Campania, Italy",
"Salerno, Salerno, Campania, Italy",
"Salisbury, Wiltshire",
"Salisbury, Wiltshire, , England",
"Salmesbury, Lancashire, England",
"Saltre Abbey, Huntingdonshire, , England",
"Saluzzo-Cuneo, Piedmont",
"Saluzzo, Cuneo, Piemonte, Italy",
"Samlesbury, Lancashire, England",
"Sanquhar, Dumfriesshire,Scotland",
"Santa Maria Donna Regina Vecchia, Naples, Naples, Campania, Italy",
"Sarria, Lugo, Galicia, Spain",
"Saunford, Hertford, England, England",
"Schwaben, Kelheim, Bayern, Germany",
"Scone, Perthshire, Scotland",
"Scotland",
"Seagrave, Leicestershire, England",
"Segrave, Leicestershire, , England",
"Sens, Yonne, France",
"Seton, East Lothian, Scotland",
"Sevilla, Andalusia, Spain",
"Sevilla, Sevilla, Andalusia, Spain",
"Sevilla, Seville, Andalucia, Spain",
"Sheffield, West Riding, Yorkshire, ENGLAND",
"Sicily",
"Sioux City, Iowa, United States of America",
"Somerset, England",
"Somerset, Pennsylvania, United States of America",
"Sopron, Hungary",
"Soria, Soria, Spain",
"Southoe, Huntingdonshire, England",
"Spain",
"Spencercombe, Devon, , England",
"St Germain,Paris,,France",
"St Pol, Nord, Nord Pas De Calais, France",
"St. Andrew's, Fife, Scotland",
"St. Clement Danes Church, Westminster, London, Middlesex, England, United Kingdom",
"St. Helena, Cedar, Nebraska, United States of America",
"St. Mary's Ridge, Wisconsin, United States of America",
"Staffordshire, England",
"Stirling Castle, Stirling, Stirlingshire, Scotland",
"Stirling, Stirlingshire, Scotland",
"Stirlingshire, Scotland",
"Stockwell, Surrey, England, United Kingdom",
"Stoke, Northamptonshire, England",
"Stommeln, Prussia, Germany",
"Strathblane, Stirlingshire, Scotland",
"Strathbogie, Aberdeenshire, Scotland",
"Stratton Audley, Oxfordshire, England.",
"Stuart, Holt, Nebraska, United States of America",
"Surrey, England, United Kingdom",
"Sussex Square, London, Middlesex, England",
"Tervueren,Brabant,,Belgium",
"Tervuren, Brabant",
"the monastery at Les Mureaux, near Meulan",
"Thrieve Castle, Galloway, Wigtonshire, Dal Riata (Dalraida), Scotland",
"Toledo, Castile",
"Toledo, Castile, Spain",
"Toledo, New Castile",
"Toledo, Spain",
"Tomb and statue at St. Denis Cathedral, north of Paris",
"Tongue, Sutherland, Scotland",
"Toro, Zamora, Castilla-Le\u00f3n, Spain",
"Totnes, Devonshire, England",
"Towcester, Northamptonshire, England",
"Trapani, Sicilia, Italia",
"Troyes, Aube, Champagne-Ardenne, France",
"Tunis, Tunisia",
"Turkey",
"Turnberry Castle, Ayrshire, Scotland",
"Ulster, Ulster, Ireland",
"United Kingdom",
"United States of America",
"Valence, Charente, Poitou-Charentes, France",
"Valladolid, Castilla-Le\u00f3n, Spain",
"Valladolid, Spain",
"Valladolid, Valladolid, Castilla-Le\u00f3n, Spain",
"Verrey,Auvergne,,France",
"Vienna, Austria",
"Villafranca del Panad\u00e9s, Catalonia, Spain",
"Ville, Paris, Ile-de-France, France",
"Virginia, United States of America",
"Walden Abbey, Walden, Essex, England, United Kingdom",
"Walden, Essex, England, United Kingdom",
"Wales",
"Warkwick, Warkwickshire, England, United Kingdom",
"Warkwickshire, England, United Kingdom",
"Warren, Sussex , England",
"Warwick Castle, Warkwick, Warkwickshire, England, United Kingdom",
"Warwick, Warwickshire, , England",
"Warwick, Warwickshire, England",
"Wendover, Buckinghamshire, , England",
"Wendover, Buckinghamshire, England",
"Werntrop, Westphalia, Hochsauerlandkreis, Germany",
"West Lothian, Scotland",
"West Riding, Yorkshire, , England",
"West Riding, Yorkshire, ENG",
"Westfalen, Prussia, Germany",
"Westminster Abbey, Westminster, London, Middlesex, England, United Kingdom",
"Westminster, London, Middlesex, England, United Kingdom",
"Westphalia, Hochsauerlandkreis, Germany",
"Wigan, Lancashire, England",
"Wigmore Castle, Herefordshire, England",
"Wigmore, Herefordshire",
"Wigmore, Herefordshire, England",
"Wigmore, Ludlow, Herefordshire",
"Winchester Castle, Winchester, Hampshire, England",
"Winterbourne Stoke, Amesbury, Wiltshire, England",
"Wisconsin, United States of America",
"Woolston, Essex, England, United Kingdom",
"Worcestershire, England",
"Worringen, Rheinland, Germany",
"Wynot, Cedar, Nebraska, United States of America",
"Y,,,",
"York Minster, York, Yorkshire, England",
"Yorkshire West Riding, England",
"\u017baga\u0144",
"Zamora, Castilla-Le\u00f3n, Spain",
"Zamora, Zamora, Castilla-Le\u00f3n, Spain",
"Zaragoza, Aragon, Spain",
"Zaragoza, Zaragoza, Aragon, Spain"
]
Dwr.ScriptLoaded('dwr_db_P_name_0.js');
